import { useState, useEffect } from "react";

const WA="573013101050",WL=`https://wa.me/${WA}`,EM="info@contarae.com",F="'Outfit',sans-serif",FH="'Libre Baskerville',serif";
const fm=n=>new Intl.NumberFormat("es-CO").format(n);
const wm=m=>`${WL}?text=${encodeURIComponent(m)}`;
const WOMPI_KEY="pub_prod_aEMHipEJ29G4pZOiIwgRC1GOvbqIYzP6";
const fmtI=v=>{const n=v.replace(/\D/g,"");return n?"$ "+fm(parseInt(n)):""};
const pN=v=>parseInt(v.replace(/\D/g,""))||0;
const getTarifa=t=>{if(t<=2000000)return 80000;if(t<=4000000)return 100000;if(t<=7000000)return 120000;if(t<=12000000)return 150000;if(t<=20000000)return 180000;return 200000};

function LogoNav(){return(<div style={{display:"flex",alignItems:"center",gap:10}}><svg width="32" height="40" viewBox="0 0 32 40"><path d="M16 0 L32 10 L32 30 L16 40 L0 30 L0 10 Z" fill="#1B3A5C" stroke="#2563EB" strokeWidth="1.5"/><path d="M16 4 L28 11 L28 29 L16 36 L4 29 L4 11 Z" fill="none" stroke="#60A5FA" strokeWidth=".8" opacity=".5"/><text x="16" y="27" textAnchor="middle" fontFamily="Georgia,serif" fontSize="20" fill="#fff" fontWeight="700">C</text></svg><div><div style={{display:"flex"}}><span style={{fontFamily:FH,fontSize:18,fontWeight:700,color:"#fff",letterSpacing:"1.5px"}}>CONTA</span><span style={{fontFamily:FH,fontSize:18,fontWeight:700,color:"#60A5FA",letterSpacing:"1.5px"}}>RAE</span></div><div style={{fontSize:7,color:"rgba(255,255,255,.55)",letterSpacing:"2.2px",fontFamily:F,marginTop:1}}>SERVICIOS CONTABLES, TRIBUTARIOS Y FINANCIEROS</div></div></div>)}
function LogoFt(){return(<div style={{display:"flex",alignItems:"center",gap:11,justifyContent:"center",marginBottom:14}}><svg width="38" height="46" viewBox="0 0 56 64"><path d="M28 0 L56 16 L56 48 L28 64 L0 48 L0 16 Z" fill="#1B3A5C" stroke="#2563EB" strokeWidth="2.5"/><path d="M28 6 L50 19 L50 45 L28 58 L6 45 L6 19 Z" fill="none" stroke="#60A5FA" strokeWidth="1.2" opacity=".5"/><text x="28" y="42" textAnchor="middle" fontFamily="Georgia,serif" fontSize="34" fill="#fff" fontWeight="700">C</text></svg><div><div style={{display:"flex"}}><span style={{fontFamily:FH,fontSize:22,fontWeight:700,color:"#fff",letterSpacing:"2px"}}>CONTA</span><span style={{fontFamily:FH,fontSize:22,fontWeight:700,color:"#60A5FA",letterSpacing:"2px"}}>RAE</span></div><div style={{height:1.5,background:"#60A5FA",opacity:.5,marginTop:3,marginBottom:5,borderRadius:2}}/><div style={{fontSize:8,color:"rgba(255,255,255,.75)",letterSpacing:"2.8px",fontFamily:F}}>SERVICIOS CONTABLES, TRIBUTARIOS Y FINANCIEROS</div></div></div>)}

const WHY=[
  {i:"⚡",t:"Respuesta inmediata",d:"Atendemos su solicitud en menos de 24 horas hábiles. Su tiempo es valioso y lo respetamos con la agilidad que necesita."},
  {i:"🎓",t:"Contadores Públicos certificados",d:"Profesionales con tarjeta profesional vigente ante la Junta Central de Contadores y experiencia comprobada en diversos sectores."},
  {i:"💻",t:"100% en línea",d:"Todos nuestros servicios se gestionan de forma digital, sin desplazamientos. Desde cualquier lugar de Colombia, a cualquier hora."},
  {i:"💲",t:"Precios transparentes",d:"Conozca el valor exacto antes de contratar. Sin costos ocultos ni sorpresas. Tarifas claras y justas desde el primer contacto."},
  {i:"🔒",t:"Confidencialidad garantizada",d:"Su información financiera está protegida conforme a la Ley 1581 de 2012 de protección de datos personales. Total reserva profesional."},
  {i:"🤝",t:"Acompañamiento permanente",d:"No solo hacemos el trámite: lo asesoramos en cada paso del camino. Somos su aliado contable y financiero de largo plazo."}
];

const SVC=[
  {i:"📊",t:"Contabilidad Integral",d:"Ciclo contable completo para microempresas, emprendedores y pymes: registro de operaciones, conciliaciones bancarias, estados financieros (balance general, estado de resultados, flujo de efectivo) y aplicación de NIIF. Información confiable y oportuna para la toma de decisiones.",w:"Hola CONTARAE, estoy interesado en el servicio de Contabilidad Integral para mi empresa. Me gustaría recibir más información."},
  {i:"📋",t:"Asesoría Tributaria",d:"Acompañamiento integral en el cumplimiento de sus obligaciones ante la DIAN: declaración de renta, IVA, retención en la fuente, ICA, información exógena y planeación tributaria estratégica. Optimizamos su carga fiscal dentro del marco legal vigente.",w:"Hola CONTARAE, necesito asesoría tributaria. Me gustaría conocer más sobre este servicio."},
  {i:"💰",t:"Gestión Financiera",d:"Diseño e implementación de herramientas de control financiero: presupuestos, análisis de flujo de caja, indicadores financieros (KPIs), análisis de costos por centro de responsabilidad, proyecciones y reportes gerenciales personalizados.",w:"Hola CONTARAE, me interesa el servicio de Gestión Financiera. Quisiera recibir más información."},
  {i:"👥",t:"Nómina y Seguridad Social",d:"Gestión integral de nómina: liquidación de salarios, prestaciones sociales (prima, cesantías, intereses, vacaciones), aportes a seguridad social (salud, pensión, ARL), planilla PILA, contratos laborales y certificados de ingresos y retenciones.",w:"Hola CONTARAE, necesito información sobre el servicio de Nómina y Seguridad Social."},
  {i:"📄",t:"Certificaciones Contables",d:"Certificados de ingresos, patrimonio, no declarante de renta y demás certificaciones contables firmadas por Contador Público con tarjeta profesional vigente. Conforme a la Ley 43 de 1990 y lineamientos del CTCP. Entrega digital inmediata en formato PDF.",w:"Hola CONTARAE, necesito una certificación contable. Me gustaría conocer los requisitos."},
  {i:"🔧",t:"Otros Servicios Contables",d:"¿Necesita un servicio contable que no aparece en esta lista? También ofrecemos: auditoría interna, elaboración de informes financieros especiales, asesoría en procesos ante la DIAN, liquidación de empresas, constitución de consorcios, revisoría del RUT y orientación en temas societarios. Consúltenos su caso particular.",w:"Hola CONTARAE, necesito información sobre un servicio contable específico que no encuentro en su página. ¿Me pueden asesorar?"}
];

const PLN=[
  {n:"Emprendedor",p:"Desde $500.000/mes",tg:"Independientes y microempresas",f:["Registro contable mensual completo","Declaraciones tributarias básicas (IVA, Rete fuente)","Conciliación bancaria mensual","Estados financieros trimestrales","Asesoría tributaria básica permanente","Soporte por WhatsApp"],w:"Hola CONTARAE, estoy interesado en el Plan Emprendedor de contabilidad para mi negocio. ¿Me pueden dar más información?"},
  {n:"Empresarial",p:"Desde $1.000.000/mes",tg:"Pequeñas y medianas empresas",f:["Todo lo del Plan Emprendedor","Liquidación de nómina y seguridad social","Estados financieros mensuales","Información exógena DIAN","Indicadores financieros y KPIs","Planeación tributaria estratégica","Soporte prioritario"],pop:true,w:"Hola CONTARAE, me interesa el Plan Empresarial de contabilidad. ¿Podrían darme más detalles?"},
  {n:"Premium",p:"Desde $2.000.000/mes",tg:"Empresas en crecimiento",f:["Todo lo del Plan Empresarial","Presupuestos y control de gestión","Dashboard financiero con Power BI","Análisis de costos por centro","Reuniones mensuales con informe gerencial","Asesor financiero dedicado","Soporte 24/7"],w:"Hola CONTARAE, quiero conocer más sobre el Plan Premium de contabilidad. ¿Me pueden asesorar?"}
];

const SCN=[
  {e:"👔",t:"Soy empleado y necesito certificación para arrendar",d:"Le piden certificación de ingresos firmada por contador para el estudio de arrendamiento. La emitimos en horas, 100% en línea.",l:"#certificacion"},
  {e:"💼",t:"Soy independiente y no sé si debo declarar renta",d:"Sus ingresos pueden obligarlo a declarar ante la DIAN. Use nuestra herramienta para verificar al instante si está obligado.",l:"#herramientas"},
  {e:"🏪",t:"Tengo una pyme y necesito organizar mi contabilidad",d:"Su empresa necesita estados financieros confiables, cumplimiento tributario y orden financiero. Nuestros planes lo cubren todo.",l:"#planes"},
  {e:"📋",t:"Me pidieron renovar la matrícula mercantil",d:"El plazo vence el 31 de marzo. No renovar genera sanciones de la Superintendencia de Sociedades. Nosotros hacemos el trámite completo.",l:"#tramites"},
  {e:"🏗️",t:"Quiero crear mi empresa legalmente en Colombia",d:"Constitución de SAS, LTDA o S.A., registro en Cámara de Comercio, RUT y todos los requisitos para operar formalmente.",l:"#tramites"},
  {e:"🧮",t:"Quiero saber cuánto me retienen o debo pagar de planilla",d:"Use nuestras herramientas de cálculo: retención en la fuente, planilla de independientes, prestaciones sociales e IVA.",l:"#herramientas"}
];

const TRM=[
  {i:"📄",t:"Certificación de Ingresos",d:"Documento firmado por Contador Público que certifica sus ingresos con base en soportes verificables. Válido ante bancos, inmobiliarias, embajadas y más. 100% online, entrega inmediata en PDF.",l:"cert",w:"Hola CONTARAE, necesito un certificado de ingresos firmado por Contador Público."},
  {i:"📝",t:"Declaración de Renta",d:"Preparación y presentación ante la DIAN para personas naturales y jurídicas. Análisis de deducciones, rentas exentas y verificación contra información exógena. Plazos 2026: 12 agosto al 26 octubre.",l:"wa",w:"Hola CONTARAE, necesito ayuda con mi declaración de renta. ¿Me pueden asesorar?"},
  {i:"🏢",t:"Renovación Matrícula Mercantil",d:"Gestión completa ante Cámara de Comercio conforme al artículo 33 del Código de Comercio. Plazo: 31 de marzo de cada año. Sanciones por incumplimiento hasta 17 SMLMV (Ley 1727 de 2014).",l:"wa",w:"Hola CONTARAE, necesito renovar mi matrícula mercantil. ¿Cuáles son los requisitos y costos?"},
  {i:"🧾",t:"Facturación Electrónica",d:"Implementación completa del sistema de facturación electrónica: habilitación ante la DIAN, proveedor tecnológico, resolución de numeración, capacitación a su equipo y soporte técnico continuo.",l:"wa",w:"Hola CONTARAE, necesito implementar facturación electrónica en mi empresa. ¿Me pueden orientar?"},
  {i:"📊",t:"Información Exógena",d:"Preparación y presentación de medios magnéticos ante la DIAN dentro de los plazos del calendario tributario. Sanciones desde $524.000 (10 UVT) hasta el 5% de las sumas no reportadas (art. 651 ET).",l:"wa",w:"Hola CONTARAE, necesito ayuda con la presentación de información exógena ante la DIAN."},
  {i:"🏗️",t:"Creación de Empresas",d:"Constitución legal completa: elección del tipo societario (SAS, LTDA, S.A.), elaboración de estatutos, registro en Cámara de Comercio, inscripción del RUT, cuenta bancaria empresarial e inscripción como responsable de IVA.",l:"wa",w:"Hola CONTARAE, quiero crear mi empresa legalmente en Colombia. ¿Cuáles son los pasos y costos?"}
];

const CT=[{r:"Hasta $2.000.000",v:80000},{r:"$2.000.001 a $4.000.000",v:100000},{r:"$4.000.001 a $7.000.000",v:120000},{r:"$7.000.001 a $12.000.000",v:150000},{r:"$12.000.001 a $20.000.000",v:180000},{r:"Más de $20.000.000",v:200000}];

/* ══════ UI ══════ */
const IS={width:"100%",padding:"12px 14px",borderRadius:9,border:"1px solid #d0d9e8",fontSize:15,fontFamily:F,outline:"none",background:"#f8fafd",boxSizing:"border-box"};
const bgs=["transparent","rgba(37,99,235,.03)","rgba(11,29,58,.02)","rgba(37,99,235,.04)","transparent","rgba(11,29,58,.02)"];
const Sec=({id,title,sub,bg,children,narrow})=>(<section id={id} style={{padding:"85px 24px",background:bg||"transparent"}}><div style={{maxWidth:narrow?920:1120,margin:"0 auto"}}>{title&&<div style={{textAlign:"center",marginBottom:48}}>{sub&&<div style={{fontSize:12,fontWeight:600,color:"#2563EB",letterSpacing:"2px",marginBottom:9,fontFamily:F}}>{sub}</div>}<h2 style={{fontFamily:FH,fontSize:"clamp(23px,3.5vw,36px)",fontWeight:700,color:"#0B1D3A"}}>{title}</h2></div>}{children}</div></section>);
const Cd=({children,s})=><div style={{padding:24,borderRadius:14,background:"#fff",border:"1px solid rgba(37,99,235,.07)",transition:"transform .3s,box-shadow .3s",...s}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-3px)";e.currentTarget.style.boxShadow="0 8px 26px rgba(37,99,235,.06)";}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="none";}}>{children}</div>;

function Nav(){const[op,sO]=useState(false);const items=[["Inicio","inicio"],["Servicios","servicios"],["Planes","planes"],["Certificación","certificacion"],["Herramientas","herramientas"],["Nosotros","nosotros"],["Blog","blog"],["Contacto","contacto"]];
return(<nav style={{position:"fixed",top:0,width:"100%",zIndex:200,padding:"14px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"rgba(8,14,27,.96)",backdropFilter:"blur(16px)",borderBottom:"1px solid rgba(96,165,250,.1)"}}><LogoNav/><div style={{display:"flex",gap:16,alignItems:"center"}} className="dk">{items.map(([l,id])=><a key={id} href={`#${id}`} style={{textDecoration:"none",color:"rgba(255,255,255,.6)",fontSize:13,fontWeight:500,fontFamily:F}} onMouseEnter={e=>e.target.style.color="#60A5FA"} onMouseLeave={e=>e.target.style.color="rgba(255,255,255,.6)"}>{l}</a>)}<a href={wm("Hola CONTARAE, me gustaría recibir asesoría sobre sus servicios contables.")} target="_blank" rel="noopener noreferrer" style={{padding:"7px 16px",borderRadius:9,background:"linear-gradient(135deg,#2563EB,#60A5FA)",color:"#fff",fontSize:13,fontWeight:600,textDecoration:"none"}}>WhatsApp</a></div>
<button onClick={()=>sO(!op)} className="hm" style={{background:"none",border:"none",cursor:"pointer",padding:6,display:"none"}} aria-label="Menú"><div style={{width:24,height:2.5,background:"#fff",marginBottom:5,transition:"all .3s",transform:op?"rotate(45deg) translate(5px,5px)":"none"}}/><div style={{width:24,height:2.5,background:"#fff",marginBottom:5,opacity:op?0:1}}/><div style={{width:24,height:2.5,background:"#fff",transition:"all .3s",transform:op?"rotate(-45deg) translate(5px,-5px)":"none"}}/></button>
{op&&<div style={{position:"absolute",top:"100%",left:0,width:"100%",background:"rgba(8,14,27,.98)",padding:"18px 24px",borderBottom:"1px solid rgba(96,165,250,.1)"}}>{items.map(([l,id])=><a key={id} href={`#${id}`} onClick={()=>sO(false)} style={{display:"block",padding:"13px 0",color:"rgba(255,255,255,.75)",fontSize:16,fontWeight:500,fontFamily:F,textDecoration:"none",borderBottom:"1px solid rgba(255,255,255,.06)"}}>{l}</a>)}<a href={wm("Hola CONTARAE, me gustaría recibir asesoría.")} target="_blank" rel="noopener noreferrer" onClick={()=>sO(false)} style={{display:"block",marginTop:14,padding:"13px 20px",borderRadius:11,background:"#25D366",color:"#fff",fontSize:15,fontWeight:600,textDecoration:"none",textAlign:"center",fontFamily:F}}>WhatsApp</a></div>}
</nav>)}

function Banner(){const[s,sS]=useState(true);if(!s)return null;return(<div style={{position:"fixed",top:68,width:"100%",zIndex:190,background:"linear-gradient(90deg,#1B3A5C,#2563EB)",padding:"5px 24px",display:"flex",alignItems:"center",justifyContent:"center",gap:10}}><span style={{fontSize:13,color:"#fff",fontFamily:F}}>🔥 <strong>¿Necesita su certificación de ingresos HOY?</strong> Solicítela ahora</span><a href="#certificacion" style={{fontSize:12,color:"#fff",fontWeight:700,background:"rgba(255,255,255,.2)",padding:"3px 12px",borderRadius:100,textDecoration:"none",fontFamily:F}}>Solicitar</a><button onClick={()=>sS(false)} style={{background:"none",border:"none",color:"rgba(255,255,255,.5)",cursor:"pointer",fontSize:16,padding:0,marginLeft:6}}>✕</button></div>)}

function Hero(){return(<section id="inicio" style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",textAlign:"center",padding:"150px 24px 80px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:"-15%",right:"-8%",width:500,height:500,borderRadius:"50%",background:"radial-gradient(circle,rgba(37,99,235,.07) 0%,transparent 70%)"}}/>
<div style={{maxWidth:780,position:"relative",zIndex:1}}><div style={{display:"inline-block",padding:"6px 20px",borderRadius:100,background:"rgba(37,99,235,.1)",fontSize:12,fontWeight:600,color:"#60A5FA",marginBottom:28,letterSpacing:"1.5px",fontFamily:F}}>CONTADORES PÚBLICOS CERTIFICADOS EN BOGOTÁ</div>
<h1 style={{fontFamily:FH,fontSize:"clamp(28px,5vw,52px)",fontWeight:700,lineHeight:1.12,color:"#0B1D3A",marginBottom:22}}>Su tranquilidad financiera <span style={{background:"linear-gradient(135deg,#1B3A5C,#60A5FA)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>comienza aquí</span></h1>
<p style={{fontSize:17,color:"#5A6F8A",lineHeight:1.75,maxWidth:620,margin:"0 auto 36px",fontFamily:F}}>Servicios contables, tributarios y financieros para empresas y personas naturales en Colombia. Outsourcing contable para microempresas, emprendedores y pymes.</p>
<div style={{marginBottom:14}}><a href="#certificacion" style={{display:"inline-block",padding:"15px 32px",borderRadius:13,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:15,fontWeight:600,textDecoration:"none",boxShadow:"0 4px 20px rgba(37,99,235,.3)",fontFamily:F,textAlign:"center",lineHeight:1.4}}>Solicite su certificado de ingresos firmado por Contador Público — rápido y seguro</a></div>
<div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap",marginBottom:12}}><a href="#planes" style={{padding:"12px 24px",borderRadius:12,color:"#1B3A5C",fontSize:14,fontWeight:600,textDecoration:"none",border:"2px solid rgba(27,58,92,.18)",fontFamily:F}}>Ver Planes de Contabilidad</a><a href="#tramites" style={{padding:"12px 24px",borderRadius:12,color:"#1B3A5C",fontSize:14,fontWeight:600,textDecoration:"none",border:"2px solid rgba(27,58,92,.18)",fontFamily:F}}>📝 Declaración de Renta</a></div>
<div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}><a href={wm("Hola CONTARAE, me gustaría recibir asesoría tributaria.")} target="_blank" rel="noopener noreferrer" style={{padding:"10px 20px",borderRadius:10,background:"rgba(37,99,235,.06)",color:"#1B3A5C",fontSize:14,fontWeight:600,textDecoration:"none",fontFamily:F}}>💬 Asesoría Tributaria</a><a href="#tramites" style={{padding:"10px 20px",borderRadius:10,background:"rgba(37,99,235,.06)",color:"#1B3A5C",fontSize:14,fontWeight:600,textDecoration:"none",fontFamily:F}}>🏗️ Crear mi Empresa</a></div>
</div></section>)}

function WhyUs(){return(<Sec title="¿Por qué elegir a CONTARAE?" sub="NUESTROS DIFERENCIALES" bg={bgs[0]}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18}}>{WHY.map((w,i)=><Cd key={i}><div style={{fontSize:28,marginBottom:8}}>{w.i}</div><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>{w.t}</h3><p style={{fontSize:14,color:"#5A6F8A",lineHeight:1.75,fontFamily:F}}>{w.d}</p></Cd>)}</div></Sec>)}

function SvcS(){return(<Sec id="servicios" title="Soluciones profesionales para su negocio" sub="NUESTROS SERVICIOS" bg={bgs[1]}><p style={{textAlign:"center",fontSize:15,color:"#5A6F8A",marginTop:-34,marginBottom:38,maxWidth:680,margin:"-34px auto 38px",fontFamily:F}}>Outsourcing contable para microempresas, emprendedores y pymes en Colombia. Cada servicio garantiza cumplimiento normativo y resultados confiables.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18}}>{SVC.map((s,i)=><Cd key={i}><div style={{fontSize:28,marginBottom:8}}>{s.i}</div><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>{s.t}</h3><p style={{fontSize:14,color:"#5A6F8A",lineHeight:1.75,fontFamily:F}}>{s.d}</p><a href={wm(s.w)} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",marginTop:10,fontSize:14,color:"#2563EB",fontWeight:600,textDecoration:"none",fontFamily:F}}>Solicitar asesoría →</a></Cd>)}</div></Sec>)}

function PlnS(){return(<Sec id="planes" title="Contabilidad integral para su empresa" sub="PLANES MENSUALES" bg={bgs[2]}><p style={{textAlign:"center",fontSize:14,color:"#5A6F8A",marginTop:-34,marginBottom:36,fontFamily:F}}>Precios de referencia según volumen de información. Contador para microempresas y emprendedores desde $500.000/mes.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:18}}>{PLN.map((p,i)=><div key={i} style={{padding:28,borderRadius:16,background:p.pop?"linear-gradient(135deg,#0B1D3A,#1B3A5C)":"#fff",border:p.pop?"none":"1px solid rgba(37,99,235,.07)",position:"relative",color:p.pop?"#fff":"#0B1D3A"}}>{p.pop&&<div style={{position:"absolute",top:-11,left:"50%",transform:"translateX(-50%)",background:"#60A5FA",color:"#fff",fontSize:10,fontWeight:700,padding:"4px 14px",borderRadius:100,fontFamily:F}}>MÁS POPULAR</div>}<h3 style={{fontSize:20,fontWeight:700,fontFamily:F}}>{p.n}</h3><div style={{fontSize:13,opacity:.6,marginBottom:10,fontFamily:F}}>{p.tg}</div><div style={{fontSize:21,fontWeight:700,marginBottom:16,fontFamily:FH,color:p.pop?"#60A5FA":"#2563EB"}}>{p.p}</div>{p.f.map((f,j)=><div key={j} style={{fontSize:14,padding:"5px 0",borderBottom:`1px solid ${p.pop?"rgba(255,255,255,.06)":"rgba(37,99,235,.05)"}`,fontFamily:F,opacity:.88}}>✓ {f}</div>)}<a href={wm(p.w)} target="_blank" rel="noopener noreferrer" style={{display:"block",marginTop:18,padding:"12px 20px",borderRadius:11,background:p.pop?"#60A5FA":"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,textDecoration:"none",textAlign:"center",fontFamily:F}}>Solicitar información</a></div>)}</div></Sec>)}

function ScnS(){return(<Sec title="¿Se identifica con alguno de estos casos?" sub="¿EN QUÉ LE PODEMOS AYUDAR?" bg={bgs[3]}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18}}>{SCN.map((s,i)=><a key={i} href={s.l} style={{textDecoration:"none",color:"inherit"}}><Cd s={{cursor:"pointer"}}><div style={{fontSize:28,marginBottom:8}}>{s.e}</div><h3 style={{fontSize:15,fontWeight:700,color:"#0B1D3A",marginBottom:5,fontFamily:F}}>{s.t}</h3><p style={{fontSize:14,color:"#5A6F8A",lineHeight:1.7,fontFamily:F}}>{s.d}</p><span style={{display:"inline-block",marginTop:8,fontSize:13,color:"#2563EB",fontWeight:600,fontFamily:F}}>Ver solución →</span></Cd></a>)}</div></Sec>)}

function TrmS(){return(<Sec id="tramites" title="Trámites más solicitados" sub="TRÁMITES CLAVE" bg={bgs[4]}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18}}>{TRM.map((t,i)=><Cd key={i}><div style={{fontSize:26,marginBottom:6}}>{t.i}</div><h3 style={{fontSize:15,fontWeight:700,color:"#0B1D3A",marginBottom:5,fontFamily:F}}>{t.t}</h3><p style={{fontSize:14,color:"#5A6F8A",lineHeight:1.75,fontFamily:F}}>{t.d}</p><a href={t.l==="cert"?"#certificacion":wm(t.w)} target={t.l==="wa"?"_blank":undefined} rel={t.l==="wa"?"noopener noreferrer":undefined} style={{display:"inline-block",marginTop:8,fontSize:13,color:"#2563EB",fontWeight:600,textDecoration:"none",fontFamily:F}}>{t.l==="cert"?"Solicitar al instante →":"Solicitar servicio →"}</a></Cd>)}</div></Sec>)}
/* ══════ CERTIFICATION ══════ */
function CrtS(){
  const[step,sStep]=useState(0);const[f,sF]=useState({n:"",td:"CC",cc:"",le:"",tel:"",em:"",dir:"",ent:"",per:"",iL:"",iP:"",iD:"",iI:"",iA:"",iR:"",iO:"",oD:"",cm:""});
  const[acc,sAcc]=useState(false);const[modal,sMod]=useState(null);
  const u=(k,v)=>sF(p=>({...p,[k]:v}));const uF=(k,v)=>sF(p=>({...p,[k]:fmtI(v)}));
  const ings=[["Ingresos laborales","iL","Salario y prestaciones de relación laboral."],["Pensiones","iP","Mesada pensional por vejez, invalidez o sobrevivencia."],["Dividendos","iD","Utilidades como socio o accionista de una sociedad."],["Inversiones","iI","Rendimientos de CDTs, fondos de inversión, acciones."],["Arriendos","iA","Cánones de arrendamiento de inmuebles de su propiedad."],["Remesas","iR","Dinero recibido periódicamente del exterior."]];
  const totalIng=ings.reduce((s,[,k])=>s+pN(f[k]),0)+pN(f.iO);
  const tarifa=getTarifa(totalIng);
  const consec=1000+Math.floor(Math.random()*100);
  const ref=`CONTARAE-${consec}`;

  const openWompi=async()=>{
    try{
      const sg=await fetch("/.netlify/functions/wompi-signature",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference:ref,amountInCents:tarifa*100,currency:"COP"})});
      const sd=await sg.json();if(!sd.signature){alert("Error generando firma. Intente nuevamente.");return;}
      const ck=new window.WidgetCheckout({currency:"COP",amountInCents:tarifa*100,reference:ref,publicKey:WOMPI_KEY,"signature:integrity":sd.signature,redirectUrl:"https://contarae.com"});
      ck.open(function(result){
        const tx=result.transaction;
        if(tx&&tx.status==="APPROVED"){
          const fd=new URLSearchParams();fd.append("form-name","certificacion");fd.append("consecutivo",ref);fd.append("nombre",f.n);fd.append("tipo_documento",f.td);fd.append("numero_documento",f.cc);fd.append("lugar_expedicion",f.le);fd.append("telefono",f.tel);fd.append("correo",f.em);fd.append("destino",f.dir);fd.append("entidad",f.ent);fd.append("periodo",f.per);fd.append("ingresos_laborales",f.iL);fd.append("pensiones",f.iP);fd.append("dividendos",f.iD);fd.append("inversiones",f.iI);fd.append("arriendos",f.iA);fd.append("remesas",f.iR);fd.append("otros_ingresos",f.iO);fd.append("otros_descripcion",f.oD);fd.append("total_ingresos","$"+fm(totalIng));fd.append("tarifa_pagada","$"+fm(tarifa));fd.append("referencia_wompi",ref);fd.append("estado_pago","APROBADO");fd.append("comentarios",f.cm);fd.append("declaracion_juramentada","ACEPTADA");
          fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:fd.toString()}).catch(()=>{});
          sMod(ref);
        }else if(tx&&tx.status==="DECLINED"){alert("Pago rechazado. Intente con otro medio de pago.");}
        else if(tx&&tx.status==="ERROR"){alert("Error en el pago. Intente nuevamente.");}
      });
    }catch(e){alert("Error de conexión. Intente nuevamente.");}
  };

  const waMsg=`Hola CONTARAE, confirmo mi solicitud de certificación de ingresos:%0AConsecutivo: ${ref}%0ANombre: ${f.n}%0ADocumento: ${f.td} ${f.cc}%0ATotal ingresos: $${fm(totalIng)}%0AValor pagado: $${fm(tarifa)}%0ADestino: ${f.ent||f.dir}%0AAdjunto mis soportes documentales.`;

  const pasos=["Datos personales","Destino","Ingresos y soportes","Confirmación y pago","Entrega en PDF"];

  return(<Sec id="certificacion" title="Certificación de ingresos por Contador Público" sub="CERTIFICADO DE INGRESOS ONLINE COLOMBIA" bg={bgs[5]} narrow>
    <p style={{textAlign:"center",fontSize:15,color:"#5A6F8A",marginTop:-34,marginBottom:10,fontFamily:F}}>Solicite su certificado de ingresos firmado por Contador Público con tarjeta profesional vigente.</p>
    <p style={{textAlign:"center",fontSize:14,color:"#5A6F8A",marginBottom:36,fontFamily:F}}>Certificado de ingresos para arriendo, crédito bancario, visa, licitaciones y más. 100% en línea, entrega inmediata en Bogotá y toda Colombia.</p>

    {/* Info blocks */}
    <div style={{display:"grid",gap:14,marginBottom:28}}>{[["¿Qué es un certificado de ingresos?","Documento suscrito por Contador Público con tarjeta profesional vigente ante la Junta Central de Contadores que certifica sus ingresos mensuales o anuales con base en soportes documentales verificables como extractos bancarios, contratos, facturas y comprobantes de pago."],["¿Por qué debe estar firmado por un Contador Público?","Según el artículo 10 de la Ley 43 de 1990, la firma otorga fe pública al documento. El CTCP (Concepto 1106/2019) ratifica que las certificaciones deben soportarse en documentación verificable. Esto le confiere plena validez ante cualquier entidad en Colombia."],["¿Para qué se necesita?","Solicitudes de crédito bancario o hipotecario, arrendamiento de inmuebles, compra de vehículo, trámites de visa ante embajadas, procesos de contratación o licitación, definición de situación militar y trámites académicos."],["¿Cuánto cuesta?","Desde $80.000 COP según el rango de ingresos mensuales a certificar. Incluye revisión profesional de soportes, elaboración del documento y firma por Contador Público. Entrega digital en PDF."]].map(([t,d],i)=><div key={i} style={{padding:22,borderRadius:12,background:"#fff",border:"1px solid rgba(37,99,235,.06)"}}><h3 style={{fontSize:15,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>{t}</h3><p style={{fontSize:14,color:"#5A6F8A",lineHeight:1.8,fontFamily:F}}>{d}</p></div>)}</div>

    {/* Tarifas */}
    <div style={{padding:24,borderRadius:14,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",marginBottom:28,color:"#fff"}}><h3 style={{fontSize:17,fontWeight:700,marginBottom:14,textAlign:"center",fontFamily:F}}>Tarifas certificado de ingresos</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:8}}>{CT.map((t,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 14px",borderRadius:7,background:"rgba(255,255,255,.07)",fontFamily:F}}><span style={{fontSize:14,opacity:.85}}>{t.r}</span><span style={{fontSize:15,fontWeight:700,color:"#60A5FA"}}>${fm(t.v)}</span></div>)}</div><div style={{marginTop:14,padding:12,borderRadius:8,background:"rgba(96,165,250,.13)",fontSize:13,fontFamily:F,display:"flex",alignItems:"center",gap:6}}>🔒 <span>Pago seguro procesado por <strong>Wompi</strong>. Tarjeta, PSE, Nequi o Daviplata.</span></div></div>

    {/* Resumen de pasos */}
    <div style={{display:"flex",gap:6,marginBottom:28,flexWrap:"wrap",justifyContent:"center"}}>{pasos.map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:28,height:28,borderRadius:"50%",background:i<=step?"#2563EB":"#e0e7f0",color:i<=step?"#fff":"#5A6F8A",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:700,fontFamily:F}}>{i+1}</div><span style={{fontSize:13,color:i<=step?"#0B1D3A":"#7A8FA8",fontWeight:i<=step?600:400,fontFamily:F}}>{p}</span>{i<4&&<span style={{color:"#d0d9e8",fontSize:16}}>→</span>}</div>)}</div>

    {/* FORM */}
    <div style={{padding:28,borderRadius:16,background:"#fff",border:"1px solid rgba(37,99,235,.08)",boxShadow:"0 5px 24px rgba(37,99,235,.04)"}}>

    {step===0&&<div><h4 style={{fontSize:15,fontWeight:700,color:"#1B3A5C",marginBottom:14,fontFamily:F}}>📋 Paso 1: Datos Personales</h4><div style={{display:"grid",gap:12}}>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Nombre completo</label><input style={IS} value={f.n} onChange={e=>u("n",e.target.value)}/></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Tipo de documento</label><select style={{...IS,cursor:"pointer"}} value={f.td} onChange={e=>u("td",e.target.value)}><option>CC</option><option>TI</option><option>CE</option><option>Pasaporte</option><option>NIT</option></select></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Número de documento</label><input style={IS} value={f.cc} onChange={e=>u("cc",e.target.value)}/></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Lugar de expedición</label><input style={IS} value={f.le} onChange={e=>u("le",e.target.value)} placeholder="Ej: Bogotá D.C."/></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Teléfono / WhatsApp</label><input style={IS} value={f.tel} onChange={e=>u("tel",e.target.value)}/></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Correo electrónico</label><input style={IS} value={f.em} onChange={e=>u("em",e.target.value)}/></div>
    </div><div style={{textAlign:"right",marginTop:16}}><button onClick={()=>f.n&&f.cc&&f.tel&&f.em?sStep(1):alert("Complete todos los campos")} style={{padding:"12px 30px",borderRadius:11,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:15,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Siguiente →</button></div></div>}

    {step===1&&<div><h4 style={{fontSize:15,fontWeight:700,color:"#1B3A5C",marginBottom:14,fontFamily:F}}>🏢 Paso 2: Destino de la Certificación</h4><div style={{display:"grid",gap:12}}>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>¿A quién va dirigida?</label><select style={{...IS,cursor:"pointer"}} value={f.dir} onChange={e=>u("dir",e.target.value)}><option value="">Seleccione...</option>{["Banco o entidad financiera","Inmobiliaria o arrendador","Embajada o trámite migratorio","Concesionario de vehículos","Entidad pública","Contratación o licitación","Otro destino"].map(o=><option key={o}>{o}</option>)}</select></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Nombre de la entidad</label><input style={IS} value={f.ent} onChange={e=>u("ent",e.target.value)} placeholder="Ej: Bancolombia, Century 21..."/></div>
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Período a certificar</label><select style={{...IS,cursor:"pointer"}} value={f.per} onChange={e=>u("per",e.target.value)}><option value="">Seleccione...</option>{["Último mes","Últimos 3 meses","Últimos 6 meses","Último año","Otro período"].map(o=><option key={o}>{o}</option>)}</select></div>
    </div><div style={{display:"flex",justifyContent:"space-between",marginTop:16}}><button onClick={()=>sStep(0)} style={{padding:"12px 22px",borderRadius:11,background:"transparent",color:"#2563EB",fontSize:15,fontWeight:600,border:"2px solid rgba(37,99,235,.2)",cursor:"pointer",fontFamily:F}}>← Atrás</button><button onClick={()=>f.dir?sStep(2):alert("Seleccione destino")} style={{padding:"12px 30px",borderRadius:11,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:15,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Siguiente →</button></div></div>}

    {step===2&&<div><h4 style={{fontSize:15,fontWeight:700,color:"#1B3A5C",marginBottom:4,fontFamily:F}}>💰 Paso 3: Detalle de Ingresos Mensuales</h4><p style={{fontSize:13,color:"#7A8FA8",marginBottom:14,fontFamily:F}}>Diligencie solo los tipos de ingreso que apliquen. El valor se formatea automáticamente en pesos colombianos.</p>
      <div style={{display:"grid",gap:12}}>{ings.map(([l,k,tip])=><div key={k}><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>{l}</label><span style={{fontSize:12,color:"#7A8FA8",fontFamily:F,display:"block",marginBottom:3}}>{tip}</span><input style={IS} value={f[k]} onChange={e=>uF(k,e.target.value)} placeholder="$ 0"/></div>)}
      <div><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Otros ingresos</label><span style={{fontSize:12,color:"#7A8FA8",fontFamily:F,display:"block",marginBottom:3}}>Honorarios, comisiones, actividades independientes u otros conceptos.</span><input style={IS} value={f.iO} onChange={e=>uF("iO",e.target.value)} placeholder="$ 0"/><input style={{...IS,marginTop:6}} value={f.oD} onChange={e=>u("oD",e.target.value)} placeholder="Describa el concepto de estos ingresos"/></div></div>

      <div style={{marginTop:18,padding:18,borderRadius:11,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:12,opacity:.55,fontFamily:F}}>TOTAL INGRESOS MENSUALES</div><div style={{fontSize:11,opacity:.4,fontFamily:F}}>Calculado automáticamente — no modificable</div></div><div style={{fontSize:24,fontWeight:700,fontFamily:F,color:"#60A5FA"}}>$ {fm(totalIng)}</div></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:12,paddingTop:12,borderTop:"1px solid rgba(255,255,255,.1)"}}><div><div style={{fontSize:12,opacity:.55,fontFamily:F}}>VALOR A PAGAR POR SU CERTIFICACIÓN</div><div style={{fontSize:11,opacity:.4,fontFamily:F}}>Según tabla de tarifas — no modificable</div></div><div style={{fontSize:22,fontWeight:700,fontFamily:F}}>$ {fm(tarifa)}</div></div></div>

      <div style={{marginTop:16,padding:16,borderRadius:10,background:"rgba(37,99,235,.04)",border:"1px dashed rgba(37,99,235,.15)"}}><h4 style={{fontSize:13,fontWeight:700,color:"#1B3A5C",marginBottom:6,fontFamily:F}}>📎 Adjunte soportes (opcional, máx 10MB)</h4><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" style={{fontSize:13,fontFamily:F}}/><div style={{marginTop:10,padding:12,borderRadius:8,background:"rgba(37,99,235,.06)"}}><p style={{fontSize:13,color:"#1B3A5C",lineHeight:1.7,fontFamily:F}}>💡 <strong>¿Aún no tiene todos los soportes?</strong> No se preocupe. Puede completar su solicitud ahora y enviarnos los documentos después por WhatsApp. Uno de nuestros profesionales le indicará exactamente qué documentos necesita según su caso.</p></div></div>

      <div style={{marginTop:12}}><label style={{fontSize:13,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Comentarios u observaciones</label><textarea style={{...IS,minHeight:60,resize:"vertical",marginTop:4}} value={f.cm} onChange={e=>u("cm",e.target.value)} placeholder="Información adicional relevante para su certificación..."/></div>

      <div style={{display:"flex",justifyContent:"space-between",marginTop:16}}><button onClick={()=>sStep(1)} style={{padding:"12px 22px",borderRadius:11,background:"transparent",color:"#2563EB",fontSize:15,fontWeight:600,border:"2px solid rgba(37,99,235,.2)",cursor:"pointer",fontFamily:F}}>← Atrás</button><button onClick={()=>totalIng>0?sStep(3):alert("Ingrese al menos un valor de ingresos")} style={{padding:"12px 30px",borderRadius:11,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:15,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Siguiente →</button></div>
    </div>}

    {step===3&&<div><h4 style={{fontSize:15,fontWeight:700,color:"#1B3A5C",marginBottom:14,fontFamily:F}}>📋 Paso 4: Resumen, Confirmación y Pago</h4>
      <div style={{padding:18,borderRadius:11,background:"#f8fafd",border:"1px solid rgba(37,99,235,.06)",marginBottom:16}}><div style={{display:"grid",gap:6,fontSize:14,fontFamily:F,color:"#3a5068"}}><div><strong>Nombre:</strong> {f.n}</div><div><strong>Documento:</strong> {f.td} {f.cc} — Expedido en: {f.le}</div><div><strong>Teléfono:</strong> {f.tel}</div><div><strong>Correo:</strong> {f.em}</div><div><strong>Destino:</strong> {f.dir} {f.ent&&`— ${f.ent}`}</div><div><strong>Período:</strong> {f.per}</div><div style={{marginTop:8,paddingTop:8,borderTop:"1px solid rgba(37,99,235,.08)"}}><strong>Total ingresos mensuales:</strong> <span style={{color:"#2563EB",fontWeight:700}}>$ {fm(totalIng)}</span></div><div><strong>Valor a pagar:</strong> <span style={{color:"#0B1D3A",fontWeight:700,fontSize:16}}>$ {fm(tarifa)}</span></div></div></div>

      <div style={{padding:18,borderRadius:11,background:"rgba(220,38,38,.03)",border:"1px solid rgba(220,38,38,.1)",marginBottom:16}}><h4 style={{fontSize:14,fontWeight:700,color:"#0B1D3A",marginBottom:10,fontFamily:F}}>CONDICIONES DEL SERVICIO</h4><div style={{fontSize:13,color:"#3a5068",lineHeight:1.85,fontFamily:F}}>
        <p style={{marginBottom:8}}><strong>1. Veracidad de la información:</strong> Declaro bajo la gravedad del juramento (art. 83 Constitución Política de Colombia) que la información suministrada refleja mi realidad económica actual. Los soportes que adjunto o adjuntaré son auténticos, confiables y reales, no han sido alterados ni falsificados.</p>
        <p style={{marginBottom:8}}><strong>2. Verificación:</strong> CONTARAE se reserva el derecho de verificar la información y los soportes. CONTARAE no certificará información que no sea verificable o que presente inconsistencias.</p>
        <p style={{marginBottom:8}}><strong>3. Política de servicio:</strong> El valor pagado corresponde al servicio profesional de revisión, verificación y elaboración de la certificación. En caso de que no pueda ser emitida por falta de información, inconsistencias o insuficiencia de soportes atribuibles al solicitante, CONTARAE no está obligada a la devolución total ni parcial del valor pagado.</p>
        <p><strong>4. Tratamiento de datos:</strong> Autorizo a CONTARAE el tratamiento de mis datos personales conforme a la Ley 1581 de 2012.</p>
      </div><label style={{display:"flex",alignItems:"flex-start",gap:8,marginTop:14,cursor:"pointer"}}><input type="checkbox" checked={acc} onChange={e=>sAcc(e.target.checked)} style={{marginTop:3,accentColor:"#2563EB",width:18,height:18}}/><span style={{fontSize:14,fontWeight:700,color:"#0B1D3A",fontFamily:F}}>He leído, entiendo y acepto las condiciones anteriores.</span></label></div>

      <div style={{textAlign:"center"}}><button onClick={()=>acc?openWompi():alert("Debe aceptar las condiciones para continuar")} disabled={!acc} style={{padding:"14px 40px",borderRadius:13,background:acc?"linear-gradient(135deg,#1B3A5C,#2563EB)":"#ccc",color:"#fff",fontSize:16,fontWeight:700,border:"none",cursor:acc?"pointer":"not-allowed",fontFamily:F,boxShadow:acc?"0 4px 20px rgba(37,99,235,.3)":"none"}}>🔒 Pagar $ {fm(tarifa)} con Wompi</button><p style={{fontSize:12,color:"#7A8FA8",marginTop:10,fontFamily:F}}>Pago seguro procesado por Wompi. Sus datos están protegidos.</p></div>
      <div style={{marginTop:14}}><button onClick={()=>sStep(2)} style={{padding:"12px 22px",borderRadius:11,background:"transparent",color:"#2563EB",fontSize:15,fontWeight:600,border:"2px solid rgba(37,99,235,.2)",cursor:"pointer",fontFamily:F}}>← Atrás</button></div>
    </div>}
    </div>

    {/* MODAL POST-PAGO */}
    {modal&&<div style={{position:"fixed",top:0,left:0,width:"100%",height:"100%",background:"rgba(0,0,0,.6)",zIndex:9999,display:"flex",alignItems:"center",justifyContent:"center",padding:24}} onClick={()=>sMod(null)}><div style={{background:"#fff",borderRadius:20,padding:36,maxWidth:520,width:"100%",textAlign:"center",boxShadow:"0 20px 60px rgba(0,0,0,.2)"}} onClick={e=>e.stopPropagation()}>
      <div style={{fontSize:52,marginBottom:14}}>✅</div>
      <h3 style={{fontSize:22,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>¡Pago confirmado!</h3>
      <div style={{display:"inline-block",padding:"6px 18px",borderRadius:100,background:"rgba(37,99,235,.1)",fontSize:16,fontWeight:700,color:"#2563EB",marginBottom:14,fontFamily:F}}>Solicitud N° {modal}</div>
      <p style={{fontSize:15,color:"#5A6F8A",lineHeight:1.8,fontFamily:F,marginBottom:8}}>Su solicitud de certificación de ingresos ha sido recibida exitosamente. Uno de nuestros Contadores Públicos revisará la información y los soportes adjuntos.</p>
      <p style={{fontSize:14,color:"#5A6F8A",fontFamily:F,marginBottom:6}}>En caso de requerirse documentación adicional, nos pondremos en contacto de inmediato por WhatsApp o correo electrónico.</p>
      <p style={{fontSize:13,color:"#7A8FA8",fontFamily:F,marginBottom:20}}>Consulte el estado de su solicitud por WhatsApp indicando su número de consecutivo: <strong>{modal}</strong></p>
      <div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}><a href={`${WL}?text=${waMsg}`} target="_blank" rel="noopener noreferrer" style={{padding:"12px 24px",borderRadius:11,background:"#25D366",color:"#fff",fontSize:14,fontWeight:600,textDecoration:"none",fontFamily:F}}>Enviar soportes por WhatsApp</a><button onClick={()=>{sMod(null);sStep(0);sAcc(false);sF({n:"",td:"CC",cc:"",le:"",tel:"",em:"",dir:"",ent:"",per:"",iL:"",iP:"",iD:"",iI:"",iA:"",iR:"",iO:"",oD:"",cm:""});}} style={{padding:"12px 24px",borderRadius:11,background:"rgba(37,99,235,.08)",color:"#2563EB",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Nueva solicitud</button><button onClick={()=>sMod(null)} style={{padding:"12px 24px",borderRadius:11,background:"transparent",color:"#5A6F8A",fontSize:14,fontWeight:600,border:"2px solid rgba(37,99,235,.12)",cursor:"pointer",fontFamily:F}}>Cerrar</button></div>
    </div></div>}
  </Sec>);
}
/* ══════ TOOLS ══════ */
function Tools(){const[tab,sTab]=useState(0);const uv=49799;
const tabs=["¿Debe declarar?","Retención en la fuente","Planilla independientes","Prestaciones sociales","Calculadora IVA","Precio antes de IVA"];
return(<Sec id="herramientas" title="Herramientas de cálculo tributario" sub="HERRAMIENTAS" bg={bgs[1]}><p style={{textAlign:"center",fontSize:15,color:"#5A6F8A",marginTop:-34,marginBottom:32,fontFamily:F}}>Calculadoras basadas en normatividad tributaria colombiana vigente. Los resultados son estimados y no reemplazan la asesoría profesional.</p>
<div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"center",marginBottom:24}}>{tabs.map((t,i)=><button key={i} onClick={()=>sTab(i)} style={{padding:"8px 16px",borderRadius:100,background:tab===i?"#2563EB":"rgba(37,99,235,.06)",color:tab===i?"#fff":"#1B3A5C",fontSize:13,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F,transition:"all .2s"}}>{t}</button>)}</div>
<div style={{maxWidth:600,margin:"0 auto"}}>

{tab===0&&<ToolRenta uv={uv}/>}
{tab===1&&<ToolRetencion uv={uv}/>}
{tab===2&&<ToolPlanilla/>}
{tab===3&&<ToolPrestaciones/>}
{tab===4&&<ToolIVA/>}
{tab===5&&<ToolPrecioIVA/>}

</div></Sec>)}

function ToolRenta({uv}){const[rF,sRF]=useState({i:"",p:"",c:"",tc:"",b:""});const[rR,sRR]=useState(null);
const chk=()=>{const v=k=>pN(rF[k]);const i=v("i"),p=v("p"),c=v("c"),tc=v("tc"),b=v("b");const t14=1400*uv,t45=4500*uv;const ob=i>t14||p>t45||c>t14||tc>t14||b>t14;const rz=[];if(i>t14)rz.push(`Ingresos ($${fm(i)}) superan 1.400 UVT ($${fm(Math.round(t14))})`);if(p>t45)rz.push(`Patrimonio ($${fm(p)}) supera 4.500 UVT ($${fm(Math.round(t45))})`);if(c>t14)rz.push(`Compras ($${fm(c)}) superan 1.400 UVT`);if(tc>t14)rz.push(`Tarjeta crédito ($${fm(tc)}) supera 1.400 UVT`);if(b>t14)rz.push(`Consignaciones ($${fm(b)}) superan 1.400 UVT`);sRR({ob,rz});};
return(<Cd s={{padding:26}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>📝 ¿Debe declarar renta 2026?</h3><p style={{fontSize:13,color:"#5A6F8A",marginBottom:16,fontFamily:F}}>Año gravable 2025 (Decreto 2229/2023). UVT 2025: $49.799.</p><div style={{display:"grid",gap:10}}>{[["Ingresos brutos anuales","i","≥ $69.718.600"],["Patrimonio a dic 31/2025","p","≥ $224.095.500"],["Compras y consumos","c","≥ $69.718.600"],["Consumos tarjeta de crédito","tc","≥ $69.718.600"],["Consignaciones bancarias","b","≥ $69.718.600"]].map(([l,k,tip])=><div key={k}><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>{l} <span style={{fontSize:12,color:"#7A8FA8",fontWeight:400}}>Tope: {tip}</span></label><input style={{...IS,marginTop:3}} value={rF[k]} onChange={e=>sRF(p=>({...p,[k]:fmtI(e.target.value)}))} placeholder="$ 0"/></div>)}<button onClick={chk} style={{padding:"11px 20px",borderRadius:10,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Verificar obligación</button></div>{rR&&<div style={{marginTop:16,padding:16,borderRadius:11,background:rR.ob?"rgba(220,38,38,.06)":"rgba(22,163,74,.06)",border:`1px solid ${rR.ob?"rgba(220,38,38,.12)":"rgba(22,163,74,.12)"}`}}><div style={{fontSize:15,fontWeight:700,color:rR.ob?"#DC2626":"#16A34A",marginBottom:6,fontFamily:F}}>{rR.ob?"⚠️ Probablemente SÍ está obligado a declarar":"✅ Posiblemente NO está obligado a declarar"}</div>{rR.rz.map((r,i)=><p key={i} style={{fontSize:13,color:"#5A6F8A",fontFamily:F}}>• {r}</p>)}<p style={{fontSize:12,color:"#7A8FA8",marginTop:8,fontFamily:F}}>* También deben declarar responsables de IVA independientemente de los montos.</p><a href={wm("Hola CONTARAE, quiero verificar si estoy obligado a declarar renta.")} target="_blank" rel="noopener noreferrer" style={{fontSize:13,color:"#2563EB",fontWeight:600,textDecoration:"none",fontFamily:F}}>Asesoría personalizada →</a></div>}</Cd>)}

function ToolRetencion({uv}){const[d,sD]=useState({ing:"",sal:"",pen:"",sol:"",vol:"",afc:"",dep:false,ded:""});const[r,sR]=useState(null);
const calc=()=>{const ig=pN(d.ing);if(ig<=0)return;const sl=pN(d.sal)||ig*.04,pn=pN(d.pen)||ig*.04,fs=pN(d.sol),vl=pN(d.vol),af=pN(d.afc),dp=d.dep?Math.min(ig*.1,32*uv):0,dd=pN(d.ded);
const deducc=sl+pn+fs+vl+af+dp+dd;const subT=Math.max(0,ig-deducc);const rEx=Math.min(subT*.25,240*uv);const base=Math.max(0,subT-rEx);const uvts=base/uv;
let ret=0;if(uvts<=95)ret=0;else if(uvts<=150)ret=(base-95*uv)*.19;else if(uvts<=360)ret=55*uv*.19+(base-150*uv)*.28;else if(uvts<=640)ret=55*uv*.19+210*uv*.28+(base-360*uv)*.33;else if(uvts<=945)ret=55*uv*.19+210*uv*.28+280*uv*.33+(base-640*uv)*.35;else if(uvts<=2300)ret=55*uv*.19+210*uv*.28+280*uv*.33+305*uv*.35+(base-945*uv)*.37;else ret=55*uv*.19+210*uv*.28+280*uv*.33+305*uv*.35+1355*uv*.37+(base-2300*uv)*.39;
sR({ig,deducc:Math.round(deducc),rEx:Math.round(rEx),base:Math.round(base),ret:Math.max(0,Math.round(ret)),tasa:ig>0?((Math.max(0,ret)/ig)*100).toFixed(1):"0"});};
return(<Cd s={{padding:26}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>🧮 Retención en la fuente (Art. 383 ET)</h3><p style={{fontSize:13,color:"#5A6F8A",marginBottom:16,fontFamily:F}}>Procedimiento 1 con rentas exentas y deducciones. UVT 2025: $49.799.</p><div style={{display:"grid",gap:10}}>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Ingreso mensual bruto</label><input style={IS} value={d.ing} onChange={e=>sD(p=>({...p,ing:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Aporte salud (4%) <span style={{fontWeight:400,fontSize:12,color:"#7A8FA8"}}>— dejar vacío para cálculo automático</span></label><input style={IS} value={d.sal} onChange={e=>sD(p=>({...p,sal:fmtI(e.target.value)}))} placeholder="Automático"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Aporte pensión (4%)</label><input style={IS} value={d.pen} onChange={e=>sD(p=>({...p,pen:fmtI(e.target.value)}))} placeholder="Automático"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Fondo solidaridad pensional</label><input style={IS} value={d.sol} onChange={e=>sD(p=>({...p,sol:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Aportes voluntarios a pensión</label><input style={IS} value={d.vol} onChange={e=>sD(p=>({...p,vol:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Aportes AFC (Ahorro para el Fomento de la Construcción)</label><input style={IS} value={d.afc} onChange={e=>sD(p=>({...p,afc:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Otras deducciones (intereses vivienda, medicina prepagada, etc.)</label><input style={IS} value={d.ded} onChange={e=>sD(p=>({...p,ded:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<label style={{display:"flex",alignItems:"center",gap:8,cursor:"pointer"}}><input type="checkbox" checked={d.dep} onChange={e=>sD(p=>({...p,dep:e.target.checked}))} style={{accentColor:"#2563EB",width:18,height:18}}/><span style={{fontSize:14,fontFamily:F,color:"#1B3A5C"}}>¿Tiene dependientes económicos? (10% del ingreso, máx 32 UVT)</span></label>
<button onClick={calc} style={{padding:"11px 20px",borderRadius:10,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Calcular retención</button>
</div>{r&&<div style={{marginTop:16,padding:18,borderRadius:11,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><div style={{display:"grid",gap:8,fontSize:14,fontFamily:F}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Ingreso bruto:</span><span style={{fontWeight:700}}>${fm(r.ig)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Total deducciones:</span><span style={{fontWeight:700}}>- ${fm(r.deducc)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Renta exenta 25%:</span><span style={{fontWeight:700}}>- ${fm(r.rEx)}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.15)"}}><span style={{opacity:.6}}>Base gravable:</span><span style={{fontWeight:700}}>${fm(r.base)}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.15)"}}><span style={{opacity:.7,fontSize:16}}>Retención estimada:</span><span style={{fontWeight:700,fontSize:20,color:"#60A5FA"}}>${fm(r.ret)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Tasa efectiva:</span><span style={{fontWeight:700}}>{r.tasa}%</span></div></div></div>}</Cd>)}

function ToolPlanilla(){const[d,sD]=useState({ing:"",arl:"1"});const[r,sR]=useState(null);
const calc=()=>{const ing=pN(d.ing);if(ing<=0)return;const ibc=Math.round(ing*.4);const sal=Math.round(ibc*.125);const pen=Math.round(ibc*.16);const arlT=[.00522,.01044,.02436,.04350,.06960];const arl=Math.round(ibc*arlT[parseInt(d.arl)-1]);const tot=sal+pen+arl;sR({ing,ibc,sal,pen,arl,tot});};
return(<Cd s={{padding:26}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>👷 Liquidador planilla independientes / contratistas</h3><p style={{fontSize:13,color:"#5A6F8A",marginBottom:16,fontFamily:F}}>Calcule el valor mensual de aportes a seguridad social sobre el IBC (40% de ingresos).</p><div style={{display:"grid",gap:10}}>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Ingresos o honorarios mensuales</label><input style={IS} value={d.ing} onChange={e=>sD(p=>({...p,ing:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Nivel de riesgo ARL</label><select style={{...IS,cursor:"pointer"}} value={d.arl} onChange={e=>sD(p=>({...p,arl:e.target.value}))}><option value="1">Riesgo I (0.522%) — Administrativo, oficinas</option><option value="2">Riesgo II (1.044%) — Comercio, educación</option><option value="3">Riesgo III (2.436%) — Manufactura, transporte</option><option value="4">Riesgo IV (4.350%) — Minería, construcción</option><option value="5">Riesgo V (6.960%) — Alto riesgo</option></select></div>
<button onClick={calc} style={{padding:"11px 20px",borderRadius:10,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Calcular planilla</button>
</div>{r&&<div style={{marginTop:16,padding:18,borderRadius:11,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><div style={{display:"grid",gap:8,fontSize:14,fontFamily:F}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Ingresos/honorarios:</span><span style={{fontWeight:700}}>${fm(r.ing)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>IBC (40%):</span><span style={{fontWeight:700}}>${fm(r.ibc)}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.1)"}}><span style={{opacity:.6}}>Salud (12.5%):</span><span>${fm(r.sal)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Pensión (16%):</span><span>${fm(r.pen)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>ARL (Riesgo {d.arl}):</span><span>${fm(r.arl)}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.15)"}}><span style={{fontSize:16}}>Total a pagar mensual:</span><span style={{fontWeight:700,fontSize:20,color:"#60A5FA"}}>${fm(r.tot)}</span></div></div></div>}</Cd>)}

function ToolPrestaciones(){const[d,sD]=useState({sal:"",dias:""});const[r,sR]=useState(null);
const calc=()=>{const s=pN(d.sal);const dd=parseInt(d.dias)||360;if(s<=0)return;const pr=Math.round(s*dd/360);const cs=Math.round(s*dd/360);const ic=Math.round(cs*.12);const vc=Math.round(s*dd/720);const pf=s>10*49799*30?0:Math.round(s*.09);const tot=pr+cs+ic+vc;sR({s,dd,pr,cs,ic,vc,pf,tot});};
return(<Cd s={{padding:26}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>📊 Liquidador de prestaciones sociales</h3><p style={{fontSize:13,color:"#5A6F8A",marginBottom:16,fontFamily:F}}>Calcule prima, cesantías, intereses de cesantías y vacaciones según salario y días trabajados.</p><div style={{display:"grid",gap:10}}>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Salario mensual</label><input style={IS} value={d.sal} onChange={e=>sD(p=>({...p,sal:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Días trabajados en el período</label><input style={IS} value={d.dias} onChange={e=>sD(p=>({...p,dias:e.target.value}))} placeholder="360 (un año completo)"/></div>
<button onClick={calc} style={{padding:"11px 20px",borderRadius:10,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Calcular prestaciones</button>
</div>{r&&<div style={{marginTop:16,padding:18,borderRadius:11,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><div style={{display:"grid",gap:8,fontSize:14,fontFamily:F}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Salario: ${fm(r.s)} | Días: {r.dd}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.1)"}}><span style={{opacity:.6}}>Prima de servicios:</span><span>${fm(r.pr)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Cesantías:</span><span>${fm(r.cs)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Intereses de cesantías (12%):</span><span>${fm(r.ic)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Vacaciones:</span><span>${fm(r.vc)}</span></div>{r.pf>0&&<div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Parafiscales (9%):</span><span>${fm(r.pf)}/mes</span></div>}<div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.15)"}}><span style={{fontSize:16}}>Total prestaciones:</span><span style={{fontWeight:700,fontSize:20,color:"#60A5FA"}}>${fm(r.tot)}</span></div></div></div>}</Cd>)}

function ToolIVA(){const[d,sD]=useState({base:"",tar:"19"});const[r,sR]=useState(null);
const calc=()=>{const b=pN(d.base);if(b<=0)return;const t=parseFloat(d.tar)/100;const iva=Math.round(b*t);sR({b,iva,tot:b+iva,tar:d.tar});};
return(<Cd s={{padding:26}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>🧾 Calculadora de IVA</h3><p style={{fontSize:13,color:"#5A6F8A",marginBottom:16,fontFamily:F}}>Calcule el IVA sobre un valor base según las tarifas del Estatuto Tributario colombiano.</p><div style={{display:"grid",gap:10}}>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Valor base (antes de IVA)</label><input style={IS} value={d.base} onChange={e=>sD(p=>({...p,base:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Tarifa de IVA</label><select style={{...IS,cursor:"pointer"}} value={d.tar} onChange={e=>sD(p=>({...p,tar:e.target.value}))}><option value="0">0% — Exento</option><option value="5">5% — Tarifa reducida</option><option value="19">19% — Tarifa general</option></select></div>
<button onClick={calc} style={{padding:"11px 20px",borderRadius:10,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Calcular IVA</button>
</div>{r&&<div style={{marginTop:16,padding:18,borderRadius:11,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><div style={{display:"grid",gap:8,fontSize:14,fontFamily:F}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Base:</span><span>${fm(r.b)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>IVA ({r.tar}%):</span><span style={{color:"#60A5FA",fontWeight:700}}>${fm(r.iva)}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.15)"}}><span style={{fontSize:16}}>Total con IVA:</span><span style={{fontWeight:700,fontSize:20}}>${fm(r.tot)}</span></div></div></div>}</Cd>)}

function ToolPrecioIVA(){const[d,sD]=useState({total:"",tar:"19"});const[r,sR]=useState(null);
const calc=()=>{const t=pN(d.total);if(t<=0)return;const tr=parseFloat(d.tar)/100;const base=Math.round(t/(1+tr));const iva=t-base;sR({t,base,iva,tar:d.tar});};
return(<Cd s={{padding:26}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:6,fontFamily:F}}>💲 Precio antes de IVA</h3><p style={{fontSize:13,color:"#5A6F8A",marginBottom:16,fontFamily:F}}>Tiene el precio final con IVA incluido y necesita desglosar el valor base y el IVA por separado.</p><div style={{display:"grid",gap:10}}>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Precio total (IVA incluido)</label><input style={IS} value={d.total} onChange={e=>sD(p=>({...p,total:fmtI(e.target.value)}))} placeholder="$ 0"/></div>
<div><label style={{fontSize:14,fontWeight:600,color:"#1B3A5C",fontFamily:F}}>Tarifa de IVA</label><select style={{...IS,cursor:"pointer"}} value={d.tar} onChange={e=>sD(p=>({...p,tar:e.target.value}))}><option value="5">5%</option><option value="19">19%</option></select></div>
<button onClick={calc} style={{padding:"11px 20px",borderRadius:10,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:14,fontWeight:600,border:"none",cursor:"pointer",fontFamily:F}}>Desglosar IVA</button>
</div>{r&&<div style={{marginTop:16,padding:18,borderRadius:11,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><div style={{display:"grid",gap:8,fontSize:14,fontFamily:F}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>Precio total:</span><span>${fm(r.t)}</span></div><div style={{display:"flex",justifyContent:"space-between",paddingTop:8,borderTop:"1px solid rgba(255,255,255,.1)"}}><span style={{opacity:.6}}>Valor antes de IVA:</span><span style={{fontWeight:700,fontSize:18}}>${fm(r.base)}</span></div><div style={{display:"flex",justifyContent:"space-between"}}><span style={{opacity:.6}}>IVA ({r.tar}%):</span><span style={{color:"#60A5FA",fontWeight:700}}>${fm(r.iva)}</span></div></div></div>}</Cd>)}

/* ══════ TIMELINE ══════ */
const TL=[
  {m:"Ene-Mar",c:"#2563EB",items:["Renovación matrícula mercantil (plazo 31 marzo)","Renta grandes contribuyentes: 1ª cuota (10-23 feb)","Retención en la fuente mensual (ene: 10-23 feb, feb: 10-24 mar)","IVA bimestral ene-feb (10-24 mar)","Impuesto al carbono ene-feb (13 mar)"]},
  {m:"Abr-May",c:"#1B3A5C",items:["Renta grandes contribuyentes: declaración + 2ª cuota (13-27 abr)","Renta personas jurídicas: declaración + 1ª cuota (12-26 may)","Información exógena grandes contribuyentes (28 abr - 13 may)","Información exógena personas jurídicas y naturales (14 may - 12 jun)","RST declaración consolidada (abril)","IVA bimestral mar-abr (12-26 may)","Impuesto al patrimonio 1ª cuota (mayo)"]},
  {m:"Jun-Jul",c:"#2563EB",items:["Renta grandes contribuyentes: 3ª cuota (10-24 jun)","Renta personas jurídicas: 2ª cuota (9-23 jul)","IVA bimestral may-jun (9-23 jul)","IVA cuatrimestral ene-abr (12-26 may)","Retención en la fuente mensual","Precios de transferencia: declaración informativa (septiembre)"]},
  {m:"Ago-Oct",c:"#0B1D3A",items:["DECLARACIÓN DE RENTA PERSONAS NATURALES (12 ago - 26 oct)","Según dos últimos dígitos del NIT: ago 12-31, sep 1-28, oct 1-26","IVA bimestral jul-ago (sep), sep-oct (nov)","IVA cuatrimestral may-ago (sep)","Retención en la fuente mensual","Impuesto al patrimonio 2ª cuota (14 sep)"]},
  {m:"Nov-Dic",c:"#1B3A5C",items:["IVA bimestral sep-oct (11-25 nov)","Retención en la fuente mensual (oct: nov, nov: 10-23 dic)","Precios de transferencia: informe país por país (15 dic)","Cierre contable año gravable 2026","Preparación información exógena siguiente año","IVA cuatrimestral sep-dic (ene 2027)"]}
];
function TlS(){const[filt,sFilt]=useState("all");
return(<Sec title="Calendario tributario DIAN 2026" sub="OBLIGACIONES TRIBUTARIAS" bg={bgs[2]}><p style={{textAlign:"center",fontSize:14,color:"#5A6F8A",marginTop:-34,marginBottom:28,fontFamily:F}}>Principales vencimientos según Decreto 2229 de 2023. Consulte las fechas exactas según su NIT en el calendario oficial de la DIAN.</p>
<div style={{display:"grid",gap:14,maxWidth:800,margin:"0 auto"}}>{TL.map((t,i)=><div key={i} style={{display:"flex",gap:16,alignItems:"flex-start"}}><div style={{minWidth:76,textAlign:"center"}}><div style={{fontSize:17,fontWeight:700,color:t.c,fontFamily:FH}}>{t.m}</div><div style={{width:3,height:40,background:t.c,margin:"6px auto",borderRadius:4,opacity:.3}}/></div><div style={{flex:1,padding:18,borderRadius:12,background:"#fff",border:"1px solid rgba(37,99,235,.06)",borderLeft:`4px solid ${t.c}`}}>{t.items.map((item,j)=><div key={j} style={{fontSize:14,color:"#3a5068",lineHeight:1.75,fontFamily:F,padding:"2px 0"}}>• {item}</div>)}</div></div>)}</div>
<p style={{textAlign:"center",marginTop:24,fontSize:14,color:"#5A6F8A",fontFamily:F}}>Además: ICA según municipio y obligaciones especiales por actividad económica. <a href={wm("Hola CONTARAE, necesito conocer mis fechas específicas del calendario tributario según mi NIT.")} target="_blank" rel="noopener noreferrer" style={{color:"#2563EB",fontWeight:600,textDecoration:"none"}}>Consulte sus fechas específicas →</a></p></Sec>)}

/* ══════ ALERTS ══════ */
const ALT=[
  {tag:"Urgente",t:"Declaración de renta personas naturales 2026: plazos del 12 de agosto al 26 de octubre según últimos dígitos del NIT",d:"Abril 2026",cl:"#DC2626",bg:"rgba(220,38,38,.07)"},
  {tag:"Importante",t:"Información exógena: vencimientos para grandes contribuyentes del 28 de abril al 13 de mayo de 2026",d:"Abril 2026",cl:"#D97706",bg:"rgba(217,119,6,.07)"},
  {tag:"DIAN",t:"UVT 2026: $52.374 — Nuevos topes aplicables para declaración de renta del año gravable 2026",d:"Marzo 2026",cl:"#2563EB",bg:"rgba(37,99,235,.07)"},
  {tag:"Normativo",t:"Reforma Laboral 2025 (Ley 2466): cambios en liquidación de nómina, prestaciones sociales y contratos laborales",d:"Marzo 2026",cl:"#2563EB",bg:"rgba(37,99,235,.07)"},
  {tag:"DIAN",t:"Nuevos topes para declarar renta año gravable 2025: UVT $49.799 — Verifique si está obligado a declarar",d:"Febrero 2026",cl:"#2563EB",bg:"rgba(37,99,235,.07)"},
  {tag:"Informativo",t:"Plazo renovación matrícula mercantil vencido el 31 de marzo de 2026. Si no renovó, gestione la renovación extemporánea para evitar sanciones",d:"Abril 2026",cl:"#5A6F8A",bg:"rgba(90,111,138,.07)"}
];
function AltS(){return(<Sec title="Alertas y novedades tributarias" sub="NOTICIAS" bg={bgs[3]}><div style={{display:"grid",gap:12,maxWidth:800,margin:"0 auto"}}>{ALT.map((a,i)=><div key={i} style={{padding:"18px 22px",borderRadius:12,background:"#fff",border:"1px solid rgba(37,99,235,.06)",display:"flex",gap:14,alignItems:"flex-start"}}><span style={{fontSize:11,fontWeight:700,color:a.cl,background:a.bg,padding:"4px 10px",borderRadius:100,fontFamily:F,whiteSpace:"nowrap"}}>{a.tag}</span><div style={{flex:1}}><h4 style={{fontSize:14,fontWeight:700,color:"#0B1D3A",lineHeight:1.55,fontFamily:F}}>{a.t}</h4><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:6}}><span style={{fontSize:12,color:"#7A8FA8",fontFamily:F}}>{a.d}</span><a href={wm(`Hola CONTARAE, necesito ayuda con: ${a.t}`)} target="_blank" rel="noopener noreferrer" style={{fontSize:12,color:"#2563EB",fontWeight:600,textDecoration:"none",fontFamily:F}}>Necesito ayuda →</a></div></div></div>)}</div></Sec>)}

/* ══════ ABOUT (EXPANDED) ══════ */
function Abt(){return(<Sec id="nosotros" title="Conozca a CONTARAE" sub="NOSOTROS" bg={bgs[4]} narrow>
<div style={{padding:28,borderRadius:15,background:"#fff",border:"1px solid rgba(37,99,235,.06)",marginBottom:18}}><h3 style={{fontSize:18,fontWeight:700,color:"#0B1D3A",marginBottom:10,fontFamily:F}}>¿Quiénes somos?</h3><p style={{fontSize:15,color:"#5A6F8A",lineHeight:1.85,fontFamily:F}}>CONTARAE es una firma de servicios contables, tributarios y financieros fundada con el propósito de brindar soluciones profesionales, accesibles y de alta calidad a microempresas, emprendedores, pymes y personas naturales en Colombia. Nuestro equipo está conformado por Contadores Públicos certificados con tarjeta profesional vigente ante la Junta Central de Contadores, con amplia experiencia en el manejo contable de empresas de diversos sectores y tamaños.</p><p style={{fontSize:15,color:"#5A6F8A",lineHeight:1.85,fontFamily:F,marginTop:12}}>Nos especializamos en outsourcing contable, asesoría tributaria, gestión financiera, certificaciones contables y acompañamiento integral en el cumplimiento de obligaciones legales y fiscales. Entendemos que cada cliente es único, por eso ofrecemos un servicio personalizado, cercano y confidencial, adaptado a las necesidades reales de cada negocio.</p></div>

<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:14,marginBottom:18}}>{[["500+","Clientes atendidos"],["1.000+","Certificaciones emitidas"],["10+","Años de experiencia"],["100%","Compromiso profesional"]].map(([n,l],i)=><div key={i} style={{textAlign:"center",padding:18,borderRadius:12,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)"}}><div style={{fontSize:26,fontWeight:700,color:"#60A5FA",fontFamily:FH}}>{n}</div><div style={{fontSize:12,color:"rgba(255,255,255,.65)",fontFamily:F,marginTop:4}}>{l}</div></div>)}</div>

<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(270px,1fr))",gap:16,marginBottom:18}}><div style={{padding:24,borderRadius:13,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:8,fontFamily:F}}>Nuestra Misión</h3><p style={{fontSize:14,lineHeight:1.8,opacity:.9,fontFamily:F}}>Brindar servicios contables, tributarios y financieros de alta calidad, con responsabilidad, oportunidad y transparencia. Contribuimos al crecimiento sostenible de nuestros clientes mediante soluciones integrales y personalizadas que garanticen el cumplimiento normativo, la optimización de recursos y la tranquilidad financiera de cada persona y empresa que deposita su confianza en nosotros.</p></div><div style={{padding:24,borderRadius:13,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff"}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:8,fontFamily:F}}>Nuestra Visión</h3><p style={{fontSize:14,lineHeight:1.8,opacity:.9,fontFamily:F}}>Ser reconocidos como una firma líder en servicios contables y financieros en Colombia, destacándonos por la innovación en nuestros procesos, el profesionalismo de nuestro equipo y la confianza que generamos en cada uno de nuestros clientes. Aspiramos a ser el aliado estratégico de largo plazo que impulse el éxito financiero de miles de empresas y emprendedores en el país.</p></div></div>

<div style={{padding:24,borderRadius:13,background:"#fff",border:"1px solid rgba(37,99,235,.06)",marginBottom:18}}><h3 style={{fontSize:16,fontWeight:700,color:"#0B1D3A",marginBottom:12,fontFamily:F}}>Nuestros Valores</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:10}}>{[["Transparencia","Comunicación clara, honesta y veraz en cada interacción con nuestros clientes."],["Responsabilidad","Cumplimiento oportuno y riguroso de cada compromiso adquirido."],["Confidencialidad","Protección absoluta de su información financiera y personal."],["Excelencia profesional","Calidad, rigor técnico y mejora continua en cada servicio."],["Compromiso","Su éxito financiero es nuestra prioridad y motivación diaria."],["Ética","Actuamos con integridad, rectitud y apego a la normatividad vigente."]].map(([v,d],i)=><div key={i} style={{padding:"12px 14px",borderRadius:9,background:"rgba(37,99,235,.04)"}}><div style={{fontSize:14,fontWeight:700,color:"#1B3A5C",fontFamily:F}}>✦ {v}</div><div style={{fontSize:13,color:"#5A6F8A",marginTop:3,lineHeight:1.6,fontFamily:F}}>{d}</div></div>)}</div></div>

<div style={{padding:24,borderRadius:13,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",color:"#fff"}}><h3 style={{fontSize:16,fontWeight:700,marginBottom:8,fontFamily:F}}>Nuestro Compromiso</h3><p style={{fontSize:15,lineHeight:1.85,opacity:.9,fontFamily:F}}>En CONTARAE entendemos que detrás de cada número hay un esfuerzo, un proyecto de vida y una familia. Por eso tratamos cada caso con la misma dedicación y responsabilidad como si fuera el nuestro. Su tranquilidad financiera es nuestra prioridad. Nos comprometemos a estar siempre disponibles, a responder con agilidad y a ofrecer soluciones reales que marquen la diferencia en la vida financiera de nuestros clientes.</p><a href={wm("Hola CONTARAE, me gustaría conocer más sobre sus servicios.")} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",marginTop:14,padding:"10px 22px",borderRadius:10,background:"#60A5FA",color:"#fff",fontSize:14,fontWeight:600,textDecoration:"none",fontFamily:F}}>Conózcanos más →</a></div>
</Sec>)}

/* ══════ BLOG ══════ */
const BLG=[
{title:"Declaración de renta personas naturales 2026: guía completa",tag:"Tributario",date:"Abril 2026",ex:"Topes, plazos, documentos y sanciones para la declaración del año gravable 2025 ante la DIAN.",content:"Plazos: 12 agosto al 26 octubre 2026 (Decreto 2229/2023).\n\nTopes año gravable 2025 (UVT $49.799):\n• Ingresos brutos ≥ $69.718.600 (1.400 UVT)\n• Patrimonio ≥ $224.095.500 (4.500 UVT)\n• Compras/consumos ≥ $69.718.600\n• Tarjeta crédito ≥ $69.718.600\n• Consignaciones ≥ $69.718.600\n\nSanciones: extemporaneidad 5% por mes (art. 641-642 ET). Mínima: $524.000 (10 UVT)."},
{title:"Renovación de matrícula mercantil: requisitos y plazos",tag:"Empresarial",date:"Marzo 2026",ex:"Plazos, requisitos y consecuencias de no renovar ante la Cámara de Comercio.",content:"Obligatoria según art. 33 Código de Comercio. Plazo: 31 de marzo.\n\nConsecuencias de no renovar:\n• Sanciones hasta 17 SMLMV (Superintendencia de Sociedades)\n• Cancelación por 5 años sin renovar (Ley 1727/2014)\n• Restricciones para créditos y licitaciones\n\nProceso 100% en línea por Cámara de Comercio o VUE."},
{title:"Certificación de ingresos en Colombia: guía completa",tag:"Certificaciones",date:"Marzo 2026",ex:"Base legal, soportes necesarios y cómo solicitarla de forma rápida y segura.",content:"Base legal: Ley 43/1990 (arts. 1 y 10), Concepto CTCP 1106/2019.\n\nSoportes según tipo:\n• Laborales: desprendibles de nómina\n• Honorarios: facturas y extractos\n• Arriendos: contratos y comprobantes\n• Pensiones: desprendible mesada\n• Inversiones: certificados entidad financiera\n\nUsos: créditos, arrendamientos, visa, licitaciones, libreta militar."},
{title:"Facturación electrónica: obligaciones y requisitos",tag:"Tributario",date:"Febrero 2026",ex:"Quiénes están obligados y cómo implementarla correctamente.",content:"Marco: Art. 616-1 ET, Resolución DIAN 000042/2020.\n\nObligados: personas jurídicas, naturales responsables de IVA, RST.\n\nRequisitos: habilitación DIAN, proveedor tecnológico, resolución de numeración, formato XML UBL 2.1, certificado digital."},
{title:"5 errores comunes en la contabilidad de pymes",tag:"Contable",date:"Enero 2026",ex:"Los errores más frecuentes de las pymes colombianas y cómo evitarlos.",content:"1. No llevar contabilidad formal (Código de Comercio, Ley 1314/2009)\n2. Mezclar finanzas personales y empresariales\n3. No conciliar bancos mensualmente\n4. Desconocer plazos tributarios (sanciones desde $524.000)\n5. No conservar soportes contables (mínimo 5 años)"},
{title:"Información exógena DIAN: ¿qué es y quién reporta?",tag:"Tributario",date:"Enero 2026",ex:"Medios magnéticos: obligados, plazos 2026 y sanciones.",content:"Reporte de operaciones con terceros ante la DIAN.\n\nPlazos 2026:\n• Grandes contribuyentes: 28 abr - 13 may\n• Personas jurídicas/naturales: 14 may - 12 jun\n\nSanciones (art. 651 ET):\n• No enviar: hasta 5% de sumas no reportadas\n• Errores: hasta 4%\n• Extemporaneidad: hasta 3%\n• Mínima: $524.000 (10 UVT)"}
];
function BlgS(){const[exp,sE]=useState(null);return(<Sec id="blog" title="Artículos y guías contables" sub="BLOG" bg={bgs[5]}><p style={{textAlign:"center",fontSize:14,color:"#5A6F8A",marginTop:-34,marginBottom:34,fontFamily:F}}>Información basada en normatividad colombiana vigente y fuentes oficiales de la DIAN.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18}}>{BLG.map((p,i)=><div key={i} style={{borderRadius:14,background:"#fff",border:"1px solid rgba(37,99,235,.06)",overflow:"hidden"}}><div style={{padding:22}}><div style={{display:"flex",gap:6,marginBottom:8}}><span style={{fontSize:10,fontWeight:600,color:"#2563EB",background:"rgba(37,99,235,.06)",padding:"3px 9px",borderRadius:100,fontFamily:F}}>{p.tag}</span><span style={{fontSize:10,color:"#7A8FA8",fontFamily:F}}>{p.date}</span></div><h3 style={{fontSize:15,fontWeight:700,color:"#0B1D3A",marginBottom:6,lineHeight:1.45,fontFamily:F}}>{p.title}</h3><p style={{fontSize:14,color:"#5A6F8A",lineHeight:1.7,fontFamily:F}}>{p.ex}</p><button onClick={()=>sE(exp===i?null:i)} style={{marginTop:10,fontSize:13,color:"#2563EB",fontWeight:600,fontFamily:F,background:"none",border:"none",cursor:"pointer",padding:0}}>{exp===i?"Cerrar ✕":"Leer más →"}</button></div>{exp===i&&<div style={{padding:"0 22px 22px",borderTop:"1px solid rgba(37,99,235,.05)"}}><div style={{paddingTop:16,fontSize:14,color:"#3a5068",lineHeight:1.9,fontFamily:F,whiteSpace:"pre-line"}}>{p.content}</div><div style={{marginTop:14,padding:12,borderRadius:8,background:"rgba(37,99,235,.04)"}}><a href={wm(`Hola CONTARAE, necesito ayuda con: ${p.title}`)} target="_blank" rel="noopener noreferrer" style={{fontSize:13,color:"#2563EB",fontWeight:600,textDecoration:"none",fontFamily:F}}>Consultar por WhatsApp →</a></div></div>}</div>)}</div></Sec>)}

/* ══════ DOWNLOADS (16) ══════ */
const DL=[
  {n:"Checklist declaración de renta PN",d:"Lista completa de documentos y soportes para preparar su declaración del año gravable 2025.",f:"PDF"},
  {n:"Calendario tributario DIAN 2026",d:"Fechas de vencimiento de todas las obligaciones tributarias nacionales.",f:"PDF"},
  {n:"Control de ingresos y gastos mensuales",d:"Plantilla para registrar ingresos y gastos mes a mes. Ideal para independientes y freelancers.",f:"Excel"},
  {n:"Conciliación de retenciones en la fuente",d:"Plantilla para cruzar retenciones practicadas vs. reportadas en el formulario 220.",f:"Excel"},
  {n:"Control de facturación mensual",d:"Registre facturas de venta y compra con cálculo automático de IVA y totales.",f:"Excel"},
  {n:"Conciliación bancaria",d:"Compare movimientos del extracto bancario con registros contables e identifique diferencias.",f:"Excel"},
  {n:"Inventario de activos fijos",d:"Registre activos con depreciación, vida útil y valor en libros actualizado.",f:"Excel"},
  {n:"Estados financieros básicos para pymes",d:"Balance general y estado de resultados listos para diligenciar conforme a NIIF.",f:"Excel"},
  {n:"Liquidación de prestaciones sociales",d:"Calcule prima, cesantías, intereses de cesantías y vacaciones según salario.",f:"Excel"},
  {n:"Control de nómina mensual",d:"Liquidación de nómina con salario, deducciones, aportes y neto a pagar.",f:"Excel"},
  {n:"Modelo certificación laboral",d:"Formato de certificación laboral listo para diligenciar con datos del empleador.",f:"Word"},
  {n:"Guía soportes certificación de ingresos",d:"Documentos requeridos según cada tipo de ingreso: laboral, pensión, arriendos, inversiones.",f:"PDF"},
  {n:"Autorización tratamiento de datos personales",d:"Formato conforme a la Ley 1581 de 2012 y Decreto 1074 de 2015.",f:"PDF"},
  {n:"Solicitud de certificación contable",d:"Modelo de solicitud formal para certificaciones de ingresos, patrimonio o no declarante.",f:"Word"},
  {n:"Checklist creación de empresa en Colombia",d:"Paso a paso con requisitos para constituir SAS, LTDA o S.A.",f:"PDF"},
  {n:"Modelo acta de constitución SAS",d:"Modelo de acta y estatutos para la constitución de una Sociedad por Acciones Simplificada.",f:"Word"}
];
function DwS(){return(<Sec title="Formatos y guías para descargar" sub="RECURSOS" bg={bgs[0]} narrow><p style={{textAlign:"center",fontSize:14,color:"#5A6F8A",marginTop:-34,marginBottom:32,fontFamily:F}}>Documentos de referencia para facilitar sus trámites contables y tributarios. Solicítelos a través de WhatsApp.</p><div style={{display:"grid",gap:10}}>{DL.map((d,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px 20px",borderRadius:12,background:"#fff",border:"1px solid rgba(37,99,235,.06)",gap:14,flexWrap:"wrap"}}><div style={{flex:1,minWidth:220}}><h4 style={{fontSize:14,fontWeight:700,color:"#0B1D3A",fontFamily:F}}>{d.n}</h4><p style={{fontSize:13,color:"#5A6F8A",marginTop:3,fontFamily:F}}>{d.d}</p></div><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:10,fontWeight:600,color:"#2563EB",background:"rgba(37,99,235,.07)",padding:"3px 10px",borderRadius:100,fontFamily:F}}>{d.f}</span><a href={wm(`Hola CONTARAE, solicito el formato: ${d.n}`)} target="_blank" rel="noopener noreferrer" style={{padding:"8px 16px",borderRadius:8,background:"linear-gradient(135deg,#1B3A5C,#2563EB)",color:"#fff",fontSize:12,fontWeight:600,textDecoration:"none",fontFamily:F,whiteSpace:"nowrap"}}>Solicitar</a></div></div>)}</div></Sec>)}

/* ══════ FAQ (20) ══════ */
const FQ=[
  {q:"¿Cuánto cuesta una certificación de ingresos?",a:"Desde $80.000 COP según el rango de ingresos mensuales a certificar. Incluye revisión profesional de soportes, elaboración del documento y firma por Contador Público con tarjeta profesional vigente ante la JCC."},
  {q:"¿Cuánto tiempo tarda la entrega del certificado?",a:"Con documentación completa y pago confirmado, la entrega se realiza en horas. Si se requiere información adicional, nuestro equipo se comunica de inmediato para agilizar el proceso."},
  {q:"¿Qué soportes necesito para la certificación de ingresos?",a:"Depende del tipo de ingreso: desprendibles de nómina (laboral), facturas y extractos (independiente), contratos y comprobantes (arriendos), certificados (inversiones), desprendible (pensión). Le indicamos exactamente qué necesita según su caso."},
  {q:"¿La certificación de ingresos tiene vigencia?",a:"Generalmente las entidades aceptan certificaciones con antigüedad máxima de 30 a 60 días. Le recomendamos confirmar con la entidad destino antes de solicitar su certificación."},
  {q:"¿Puedo solicitar la certificación si soy independiente?",a:"Sí. Certificamos ingresos de trabajadores independientes, freelancers, contratistas y personas con ingresos por honorarios, basados en sus extractos bancarios, facturas y demás soportes verificables."},
  {q:"¿Qué pasa si mis soportes están incompletos?",a:"Puede solicitar su certificación y enviar los soportes posteriormente por WhatsApp. Nuestro equipo le indicará exactamente qué documentos necesita. No es necesario tener todo al momento de la solicitud."},
  {q:"¿Cómo sé si debo declarar renta?",a:"Depende de sus ingresos, patrimonio, compras, consumos con tarjeta de crédito y consignaciones bancarias del año gravable. Use nuestra herramienta en la sección Herramientas para verificar al instante."},
  {q:"¿Qué documentos necesito para declarar renta?",a:"Certificado de ingresos y retenciones (formulario 220), extractos bancarios de todas sus cuentas, certificados de inversiones, información de bienes y deudas, y certificados de aportes a salud, pensión y aportes voluntarios."},
  {q:"¿Qué pasa si no declaro renta a tiempo?",a:"Se genera sanción por extemporaneidad del 5% del impuesto a cargo por cada mes o fracción de retraso (art. 641-642 ET). La sanción mínima para 2026 es de $524.000 (10 UVT). Adicionalmente, la DIAN puede imponer sanción por no declarar."},
  {q:"¿Puedo corregir mi declaración si tiene errores?",a:"Sí. La DIAN permite presentar declaraciones de corrección dentro de los plazos establecidos por ley. Si la corrección aumenta el impuesto, se genera sanción por corrección del 10% de la diferencia."},
  {q:"¿Cómo funciona el plan mensual de contabilidad?",a:"Elija el plan que se ajuste al tamaño de su empresa. Nos encargamos de toda la gestión contable, tributaria y financiera de forma permanente con reportes periódicos y asesoría continua. Los precios dependen del volumen de información."},
  {q:"¿Puedo contratar un servicio puntual sin plan mensual?",a:"Sí. Ofrecemos certificaciones de ingresos, declaraciones de renta, renovación de matrícula mercantil, creación de empresas y cualquier trámite contable o tributario específico sin necesidad de plan mensual."},
  {q:"¿Qué incluye el outsourcing contable para pymes?",a:"Registro de operaciones, conciliaciones bancarias, estados financieros, declaraciones tributarias, asesoría permanente y cumplimiento de todas las obligaciones contables y fiscales de su empresa conforme a NIIF."},
  {q:"¿Cuánto tarda la renovación de matrícula mercantil?",a:"De 1 a 3 días hábiles con documentación completa (información financiera a dic 31, códigos CIIU, datos actualizados). Recomendamos hacerlo antes del 31 de marzo para evitar sanciones."},
  {q:"¿Qué necesito para crear mi empresa en Colombia?",a:"Documento de identidad, definir tipo societario (SAS es el más común), nombre de la empresa verificado en RUES, capital inicial, objeto social y dirección. Nosotros gestionamos todo el proceso ante Cámara de Comercio y DIAN."},
  {q:"¿Me ayudan con la facturación electrónica?",a:"Sí. Realizamos la habilitación ante la DIAN, selección del proveedor tecnológico, configuración de resolución de numeración, capacitación a su equipo y soporte técnico continuo."},
  {q:"¿Qué medios de pago aceptan?",a:"Pagos seguros a través de Wompi: tarjeta de crédito, tarjeta débito, PSE, Nequi y Daviplata. También aceptamos transferencia bancaria directa."},
  {q:"¿Cómo envío mis documentos o soportes?",a:"Puede adjuntar archivos directamente en el formulario de solicitud (máx 10MB) o enviarlos por WhatsApp al +57 301 310 1050. Los archivos pesados se reciben mejor por WhatsApp."},
  {q:"¿Mis datos están seguros?",a:"Sí. Cumplimos con la Ley 1581 de 2012 de protección de datos personales. Su información financiera está protegida con medidas de seguridad técnicas, humanas y administrativas. Consulte nuestra Política de Tratamiento de Datos completa."},
  {q:"¿Qué es la información exógena y quién debe reportarla?",a:"Son los medios magnéticos: reporte detallado de operaciones con terceros ante la DIAN. Obligatorio para contribuyentes que superen los topes de ingresos establecidos por resolución DIAN cada año. Su incumplimiento genera sanciones significativas."}
];
function FaqS(){const[o,sO]=useState(null);return(<Sec id="faq" title="Preguntas frecuentes" sub="RESOLVEMOS SUS DUDAS" bg={bgs[1]} narrow><div style={{display:"grid",gap:9}}>{FQ.map((f,i)=><div key={i} style={{borderRadius:11,background:"#fff",border:"1px solid rgba(37,99,235,.06)",overflow:"hidden",cursor:"pointer"}} onClick={()=>sO(o===i?null:i)}><div style={{padding:"15px 20px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:15,fontWeight:600,color:"#0B1D3A",fontFamily:F,flex:1}}>{f.q}</span><span style={{fontSize:17,color:"#2563EB",transform:o===i?"rotate(45deg)":"rotate(0)",transition:"transform .3s",marginLeft:10}}>+</span></div>{o===i&&<div style={{padding:"0 20px 15px",fontSize:14,color:"#5A6F8A",lineHeight:1.8,fontFamily:F}}>{f.a}</div>}</div>)}</div></Sec>)}

/* ══════ PRIVACY ══════ */
const PV=[
  {t:"1. Responsable",c:`CONTARAE — Servicios Contables, Tributarios y Financieros. Bogotá D.C., Colombia. ${EM}. +57 301 310 1050.`},
  {t:"2. Marco Normativo",c:"Constitución Política (art. 15), Ley 1581/2012, Decreto 1074/2015."},
  {t:"3. Definiciones",c:"Art. 3 Ley 1581/2012: Dato personal, dato sensible, titular, responsable, encargado, tratamiento, autorización, base de datos."},
  {t:"4. Principios",c:"Legalidad, finalidad, libertad, veracidad, transparencia, acceso restringido, seguridad, confidencialidad."},
  {t:"5. Datos Recopilados",c:"Identificación, contacto, financieros/tributarios y laborales cuando sean necesarios para los servicios."},
  {t:"6. Finalidades",c:"Servicios contables, certificaciones, declaraciones DIAN, nómina, comunicación, facturación, consultas y obligaciones legales."},
  {t:"7. Derechos del Titular",c:"Conocer, actualizar, rectificar, solicitar prueba de autorización, ser informado, quejas ante SIC, revocar, acceso gratuito (art. 8)."},
  {t:"8. Autorización",c:"Previa, expresa e informada por formularios, sitio web o WhatsApp. Conservada conforme art. 9 y Decreto 1074/2015."},
  {t:"9. Datos Sensibles",c:"No se recopilan sistemáticamente. En caso excepcional, autorización expresa conforme arts. 5 y 6."},
  {t:"10. Menores",c:"No se tratan salvo necesidad del representante legal, conforme art. 7."},
  {t:"11. Deberes",c:"Garantizar habeas data, conservar autorización, informar, veracidad, seguridad, rectificación, tramitar consultas/reclamos (art. 17)."},
  {t:"12. Seguridad",c:"Medidas técnicas (cifrado, respaldos), humanas (capacitación, confidencialidad) y administrativas (procedimientos, controles)."},
  {t:"13. Transferencia",c:"Solo por cumplimiento legal o autorización expresa. Internacional conforme art. 26."},
  {t:"14. Consultas y Reclamos",c:`Consultas: 10 días hábiles (prorrogable 5). Reclamos: 15 días hábiles (prorrogable 8). Canal: ${EM}.`},
  {t:"15. Canales",c:`Correo: ${EM}. WhatsApp: +57 301 310 1050. Bogotá D.C. Lun-Vie 8am-6pm.`},
  {t:"16. Vigencia",c:"Desde su publicación. Datos conservados según finalidades y obligaciones legales."},
  {t:"17. Autoridad",c:"SIC — Delegatura para Protección de Datos Personales. www.sic.gov.co. 01 8000 910 165."}
];
function Prv(){const[s,sS]=useState(false);return(<div style={{maxWidth:900,margin:"0 auto",padding:"0 24px"}}><div style={{textAlign:"center",marginBottom:16}}><button onClick={()=>sS(!s)} style={{background:"none",border:"none",color:"rgba(255,255,255,.7)",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:F,textDecoration:"underline"}}>{s?"Ocultar":"Consultar"} Política de Datos</button></div>{s&&<div style={{padding:26,borderRadius:14,background:"rgba(255,255,255,.05)",border:"1px solid rgba(96,165,250,.1)",marginBottom:20}}><h3 style={{fontFamily:FH,fontSize:18,fontWeight:700,color:"#fff",marginBottom:18,textAlign:"center"}}>Política de Tratamiento de Datos Personales</h3>{PV.map((p,i)=><div key={i} style={{marginBottom:14}}><h4 style={{fontSize:14,fontWeight:700,color:"#60A5FA",marginBottom:4,fontFamily:F}}>{p.t}</h4><p style={{fontSize:13,color:"rgba(255,255,255,.65)",lineHeight:1.85,fontFamily:F}}>{p.c}</p></div>)}<p style={{fontSize:10,color:"rgba(255,255,255,.35)",textAlign:"center",fontFamily:F}}>Última actualización: Abril 2026</p></div>}</div>)}

/* ══════ FOOTER ══════ */
function Ftr(){return(<><section id="contacto" style={{padding:"85px 24px"}}><div style={{maxWidth:660,margin:"0 auto",textAlign:"center",padding:"52px 34px",borderRadius:20,background:"linear-gradient(135deg,#0B1D3A,#1B3A5C)",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-40,right:-40,width:160,height:160,borderRadius:"50%",background:"rgba(96,165,250,.1)"}}/>
<h2 style={{fontFamily:FH,fontSize:"clamp(21px,3.5vw,32px)",fontWeight:700,color:"#fff",marginBottom:12,position:"relative"}}>¿Listo para ordenar sus finanzas?</h2><p style={{fontSize:15,color:"rgba(255,255,255,.65)",marginBottom:26,fontFamily:F,position:"relative"}}>Contadores Públicos certificados en Bogotá a su servicio.</p>
<div style={{display:"flex",gap:12,justifyContent:"center",flexWrap:"wrap",position:"relative"}}><a href={wm("Hola CONTARAE, me gustaría recibir asesoría sobre mis necesidades contables.")} target="_blank" rel="noopener noreferrer" style={{padding:"13px 28px",borderRadius:12,background:"#25D366",color:"#fff",fontSize:15,fontWeight:700,textDecoration:"none",fontFamily:F}}>WhatsApp</a><a href={`mailto:${EM}`} style={{padding:"13px 28px",borderRadius:12,background:"rgba(255,255,255,.1)",color:"#fff",fontSize:15,fontWeight:600,textDecoration:"none",border:"1px solid rgba(255,255,255,.16)",fontFamily:F}}>Correo</a></div></div></section>

<footer style={{padding:"44px 24px 32px",background:"#080E1B"}}><LogoFt/><div style={{maxWidth:620,margin:"0 auto",textAlign:"center"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:12,marginBottom:20}}><div style={{fontSize:14,color:"rgba(255,255,255,.6)",fontFamily:F}}>📱 <strong style={{color:"#fff"}}>WhatsApp:</strong> +57 301 310 1050</div><div style={{fontSize:14,color:"rgba(255,255,255,.6)",fontFamily:F}}>✉️ <strong style={{color:"#fff"}}>Correo:</strong> {EM}</div><div style={{fontSize:14,color:"rgba(255,255,255,.6)",fontFamily:F}}>📍 <strong style={{color:"#fff"}}>Ubicación:</strong> Bogotá D.C., Colombia</div><div style={{fontSize:14,color:"rgba(255,255,255,.6)",fontFamily:F}}>🕐 <strong style={{color:"#fff"}}>Horario:</strong> Lun-Vie 8am a 6pm</div></div><Prv/><div style={{borderTop:"1px solid rgba(96,165,250,.1)",paddingTop:18,marginTop:12}}><p style={{fontSize:11,color:"rgba(255,255,255,.35)",fontFamily:F}}>© 2026 CONTARAE · Bogotá D.C., Colombia · Todos los derechos reservados</p><p style={{fontSize:11,color:"rgba(255,255,255,.3)",marginTop:4,fontFamily:F}}>Ley 1581 de 2012 — Protección de Datos Personales</p></div></div></footer></>)}

/* ══════ FLOATS ══════ */
function Flt(){const[s,sS]=useState(false);useEffect(()=>{const h=()=>sS(window.scrollY>400);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
return(<>{/* WhatsApp */}<a href={wm("Hola CONTARAE, me gustaría recibir asesoría.")} target="_blank" rel="noopener noreferrer" style={{position:"fixed",bottom:28,right:28,zIndex:1000,width:58,height:58,borderRadius:"50%",background:"#25D366",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"0 4px 18px rgba(37,211,102,.4)",textDecoration:"none",fontSize:27}} aria-label="WhatsApp">💬</a>
{s&&<button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} style={{position:"fixed",bottom:28,left:28,zIndex:1000,width:46,height:46,borderRadius:"50%",background:"rgba(11,29,58,.85)",border:"1px solid rgba(96,165,250,.2)",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",fontSize:19,color:"#60A5FA",boxShadow:"0 3px 14px rgba(0,0,0,.2)"}} aria-label="Subir">↑</button>}</>)}

/* ══════ APP ══════ */
export default function App(){
  useEffect(()=>{const obs=new IntersectionObserver(en=>{en.forEach(e=>{if(e.isIntersecting){e.target.style.opacity="1";e.target.style.transform="translateY(0)";}});},{threshold:.07});setTimeout(()=>{document.querySelectorAll(".ai").forEach(el=>{el.style.opacity="0";el.style.transform="translateY(18px)";el.style.transition="opacity .6s ease,transform .6s ease";obs.observe(el);});},100);return()=>obs.disconnect();},[]);
  return(<div style={{fontFamily:F,color:"#0B1D3A",background:"#f8fafd",minHeight:"100vh"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Outfit:wght@300;400;500;600;700&display=swap');*{margin:0;padding:0;box-sizing:border-box;}html{scroll-behavior:smooth;}::selection{background:#2563EB;color:#fff;}@media(max-width:768px){.dk{display:none!important;}.hm{display:block!important;}}`}</style>
    <script src="https://checkout.wompi.co/widget.js" async></script>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService","name":"CONTARAE","description":"Certificación de ingresos por Contador Público, servicios contables, tributarios y financieros para microempresas, emprendedores y pymes en Colombia.","url":"https://contarae.com","telephone":"+573013101050","email":"info@contarae.com","address":{"@type":"PostalAddress","addressLocality":"Bogotá","addressCountry":"CO"},"areaServed":"CO","priceRange":"$$","openingHours":"Mo-Fr 08:00-18:00","serviceType":["Certificación de ingresos","Contabilidad","Asesoría tributaria","Declaración de renta","Gestión financiera","Nómina"]})}}/>
    <Nav/><Banner/>
    <form name="certificacion" data-netlify="true" hidden><input name="form-name" type="hidden" value="certificacion"/><input name="consecutivo"/><input name="nombre"/><input name="tipo_documento"/><input name="numero_documento"/><input name="lugar_expedicion"/><input name="telefono"/><input name="correo"/><input name="destino"/><input name="entidad"/><input name="periodo"/><input name="ingresos_laborales"/><input name="pensiones"/><input name="dividendos"/><input name="inversiones"/><input name="arriendos"/><input name="remesas"/><input name="otros_ingresos"/><input name="otros_descripcion"/><input name="total_ingresos"/><input name="tarifa_pagada"/><input name="referencia_wompi"/><input name="estado_pago"/><input name="comentarios"/><input name="declaracion_juramentada"/></form>
    <Hero/>
    <div className="ai"><WhyUs/></div>
    <div className="ai"><SvcS/></div>
    <div className="ai"><PlnS/></div>
    <div className="ai"><ScnS/></div>
    <div className="ai"><TrmS/></div>
    <div className="ai"><CrtS/></div>
    <div className="ai"><Tools/></div>
    <div className="ai"><TlS/></div>
    <div className="ai"><AltS/></div>
    <div className="ai"><Abt/></div>
    <div className="ai"><BlgS/></div>
    <div className="ai"><DwS/></div>
    <div className="ai"><FaqS/></div>
    <div className="ai"><Ftr/></div>
    <Flt/>
  </div>);
}
